//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.10 at 10:15:41 PM EDT 
//


package net.edmacdonald.fantasyGrounds.character.fourthEdition.jpg;

import net.edmacdonald.fantasyGrounds.character.fourthEdition.jpg.Abilities;
import net.edmacdonald.fantasyGrounds.character.fourthEdition.jpg.Actionpoints;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}abilities"/>
 *         &lt;element ref="{}actionpoints"/>
 *         &lt;element ref="{}attacks"/>
 *         &lt;element ref="{}class"/>
 *         &lt;element ref="{}coins"/>
 *         &lt;element ref="{}combattoken"/>
 *         &lt;element ref="{}defenses"/>
 *         &lt;element ref="{}encumbrance"/>
 *         &lt;element ref="{}exp"/>
 *         &lt;element ref="{}expneeded"/>
 *         &lt;element ref="{}featlist"/>
 *         &lt;element ref="{}hp"/>
 *         &lt;element ref="{}initiative"/>
 *         &lt;element ref="{}inventorylist"/>
 *         &lt;element ref="{}level"/>
 *         &lt;element ref="{}levelbonus"/>
 *         &lt;element ref="{}name"/>
 *         &lt;element ref="{}passiveinsight"/>
 *         &lt;element ref="{}passiveperception"/>
 *         &lt;element ref="{}powerfocus"/>
 *         &lt;element ref="{}powermode"/>
 *         &lt;element ref="{}powers"/>
 *         &lt;element ref="{}powershow"/>
 *         &lt;element ref="{}proficiencyarmor"/>
 *         &lt;element ref="{}proficiencyweapon"/>
 *         &lt;element ref="{}race"/>
 *         &lt;element ref="{}skilllist"/>
 *         &lt;element ref="{}specialabilitylist"/>
 *         &lt;element ref="{}speed"/>
 *         &lt;element ref="{}weaponlist"/>
 *       &lt;/sequence>
 *       &lt;attribute name="portrait" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "abilities",
    "actionpoints",
    "attacks",
    "clazz",
    "coins",
    "combattoken",
    "defenses",
    "encumbrance",
    "exp",
    "expneeded",
    "featlist",
    "hp",
    "initiative",
    "inventorylist",
    "level",
    "levelbonus",
    "name",
    "passiveinsight",
    "passiveperception",
    "powerfocus",
    "powermode",
    "powers",
    "powershow",
    "proficiencyarmor",
    "proficiencyweapon",
    "race",
    "skilllist",
    "specialabilitylist",
    "speed",
    "weaponlist"
})
@XmlRootElement(name = "character")
public class Character {

    @XmlElement(required = true)
    protected Abilities abilities;
    @XmlElement(required = true)
    protected Actionpoints actionpoints;
    @XmlElement(required = true)
    protected Attacks attacks;
    @XmlElement(name = "class", required = true)
    protected Class clazz;
    @XmlElement(required = true)
    protected Coins coins;
    @XmlElement(required = true)
    protected Combattoken combattoken;
    @XmlElement(required = true)
    protected Defenses defenses;
    @XmlElement(required = true)
    protected Encumbrance encumbrance;
    @XmlElement(required = true)
    protected Exp exp;
    @XmlElement(required = true)
    protected Expneeded expneeded;
    @XmlElement(required = true)
    protected Featlist featlist;
    @XmlElement(required = true)
    protected Hp hp;
    @XmlElement(required = true)
    protected Initiative initiative;
    @XmlElement(required = true)
    protected Inventorylist inventorylist;
    @XmlElement(required = true)
    protected Level level;
    @XmlElement(required = true)
    protected Levelbonus levelbonus;
    @XmlElement(required = true)
    protected Name name;
    @XmlElement(required = true)
    protected Passiveinsight passiveinsight;
    @XmlElement(required = true)
    protected Passiveperception passiveperception;
    @XmlElement(required = true)
    protected Powerfocus powerfocus;
    @XmlElement(required = true)
    protected Powermode powermode;
    @XmlElement(required = true)
    protected Powers powers;
    @XmlElement(required = true)
    protected Powershow powershow;
    @XmlElement(required = true)
    protected Proficiencyarmor proficiencyarmor;
    @XmlElement(required = true)
    protected Proficiencyweapon proficiencyweapon;
    @XmlElement(required = true)
    protected Race race;
    @XmlElement(required = true)
    protected Skilllist skilllist;
    @XmlElement(required = true)
    protected Specialabilitylist specialabilitylist;
    @XmlElement(required = true)
    protected Speed speed;
    @XmlElement(required = true)
    protected Weaponlist weaponlist;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String portrait;

    /**
     * Gets the value of the abilities property.
     * 
     * @return
     *     possible object is
     *     {@link Abilities }
     *     
     */
    public Abilities getAbilities() {
        return abilities;
    }

    /**
     * Sets the value of the abilities property.
     * 
     * @param value
     *     allowed object is
     *     {@link Abilities }
     *     
     */
    public void setAbilities(Abilities value) {
        this.abilities = value;
    }

    /**
     * Gets the value of the actionpoints property.
     * 
     * @return
     *     possible object is
     *     {@link Actionpoints }
     *     
     */
    public Actionpoints getActionpoints() {
        return actionpoints;
    }

    /**
     * Sets the value of the actionpoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link Actionpoints }
     *     
     */
    public void setActionpoints(Actionpoints value) {
        this.actionpoints = value;
    }

    /**
     * Gets the value of the attacks property.
     * 
     * @return
     *     possible object is
     *     {@link Attacks }
     *     
     */
    public Attacks getAttacks() {
        return attacks;
    }

    /**
     * Sets the value of the attacks property.
     * 
     * @param value
     *     allowed object is
     *     {@link Attacks }
     *     
     */
    public void setAttacks(Attacks value) {
        this.attacks = value;
    }

    /**
     * Gets the value of the clazz property.
     * 
     * @return
     *     possible object is
     *     {@link Class }
     *     
     */
    public Class getClazz() {
        return clazz;
    }

    /**
     * Sets the value of the clazz property.
     * 
     * @param value
     *     allowed object is
     *     {@link Class }
     *     
     */
    public void setClazz(Class value) {
        this.clazz = value;
    }

    /**
     * Gets the value of the coins property.
     * 
     * @return
     *     possible object is
     *     {@link Coins }
     *     
     */
    public Coins getCoins() {
        return coins;
    }

    /**
     * Sets the value of the coins property.
     * 
     * @param value
     *     allowed object is
     *     {@link Coins }
     *     
     */
    public void setCoins(Coins value) {
        this.coins = value;
    }

    /**
     * Gets the value of the combattoken property.
     * 
     * @return
     *     possible object is
     *     {@link Combattoken }
     *     
     */
    public Combattoken getCombattoken() {
        return combattoken;
    }

    /**
     * Sets the value of the combattoken property.
     * 
     * @param value
     *     allowed object is
     *     {@link Combattoken }
     *     
     */
    public void setCombattoken(Combattoken value) {
        this.combattoken = value;
    }

    /**
     * Gets the value of the defenses property.
     * 
     * @return
     *     possible object is
     *     {@link Defenses }
     *     
     */
    public Defenses getDefenses() {
        return defenses;
    }

    /**
     * Sets the value of the defenses property.
     * 
     * @param value
     *     allowed object is
     *     {@link Defenses }
     *     
     */
    public void setDefenses(Defenses value) {
        this.defenses = value;
    }

    /**
     * Gets the value of the encumbrance property.
     * 
     * @return
     *     possible object is
     *     {@link Encumbrance }
     *     
     */
    public Encumbrance getEncumbrance() {
        return encumbrance;
    }

    /**
     * Sets the value of the encumbrance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Encumbrance }
     *     
     */
    public void setEncumbrance(Encumbrance value) {
        this.encumbrance = value;
    }

    /**
     * Gets the value of the exp property.
     * 
     * @return
     *     possible object is
     *     {@link Exp }
     *     
     */
    public Exp getExp() {
        return exp;
    }

    /**
     * Sets the value of the exp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Exp }
     *     
     */
    public void setExp(Exp value) {
        this.exp = value;
    }

    /**
     * Gets the value of the expneeded property.
     * 
     * @return
     *     possible object is
     *     {@link Expneeded }
     *     
     */
    public Expneeded getExpneeded() {
        return expneeded;
    }

    /**
     * Sets the value of the expneeded property.
     * 
     * @param value
     *     allowed object is
     *     {@link Expneeded }
     *     
     */
    public void setExpneeded(Expneeded value) {
        this.expneeded = value;
    }

    /**
     * Gets the value of the featlist property.
     * 
     * @return
     *     possible object is
     *     {@link Featlist }
     *     
     */
    public Featlist getFeatlist() {
        return featlist;
    }

    /**
     * Sets the value of the featlist property.
     * 
     * @param value
     *     allowed object is
     *     {@link Featlist }
     *     
     */
    public void setFeatlist(Featlist value) {
        this.featlist = value;
    }

    /**
     * Gets the value of the hp property.
     * 
     * @return
     *     possible object is
     *     {@link Hp }
     *     
     */
    public Hp getHp() {
        return hp;
    }

    /**
     * Sets the value of the hp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Hp }
     *     
     */
    public void setHp(Hp value) {
        this.hp = value;
    }

    /**
     * Gets the value of the initiative property.
     * 
     * @return
     *     possible object is
     *     {@link Initiative }
     *     
     */
    public Initiative getInitiative() {
        return initiative;
    }

    /**
     * Sets the value of the initiative property.
     * 
     * @param value
     *     allowed object is
     *     {@link Initiative }
     *     
     */
    public void setInitiative(Initiative value) {
        this.initiative = value;
    }

    /**
     * Gets the value of the inventorylist property.
     * 
     * @return
     *     possible object is
     *     {@link Inventorylist }
     *     
     */
    public Inventorylist getInventorylist() {
        return inventorylist;
    }

    /**
     * Sets the value of the inventorylist property.
     * 
     * @param value
     *     allowed object is
     *     {@link Inventorylist }
     *     
     */
    public void setInventorylist(Inventorylist value) {
        this.inventorylist = value;
    }

    /**
     * Gets the value of the level property.
     * 
     * @return
     *     possible object is
     *     {@link Level }
     *     
     */
    public Level getLevel() {
        return level;
    }

    /**
     * Sets the value of the level property.
     * 
     * @param value
     *     allowed object is
     *     {@link Level }
     *     
     */
    public void setLevel(Level value) {
        this.level = value;
    }

    /**
     * Gets the value of the levelbonus property.
     * 
     * @return
     *     possible object is
     *     {@link Levelbonus }
     *     
     */
    public Levelbonus getLevelbonus() {
        return levelbonus;
    }

    /**
     * Sets the value of the levelbonus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Levelbonus }
     *     
     */
    public void setLevelbonus(Levelbonus value) {
        this.levelbonus = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link Name }
     *     
     */
    public Name getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link Name }
     *     
     */
    public void setName(Name value) {
        this.name = value;
    }

    /**
     * Gets the value of the passiveinsight property.
     * 
     * @return
     *     possible object is
     *     {@link Passiveinsight }
     *     
     */
    public Passiveinsight getPassiveinsight() {
        return passiveinsight;
    }

    /**
     * Sets the value of the passiveinsight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Passiveinsight }
     *     
     */
    public void setPassiveinsight(Passiveinsight value) {
        this.passiveinsight = value;
    }

    /**
     * Gets the value of the passiveperception property.
     * 
     * @return
     *     possible object is
     *     {@link Passiveperception }
     *     
     */
    public Passiveperception getPassiveperception() {
        return passiveperception;
    }

    /**
     * Sets the value of the passiveperception property.
     * 
     * @param value
     *     allowed object is
     *     {@link Passiveperception }
     *     
     */
    public void setPassiveperception(Passiveperception value) {
        this.passiveperception = value;
    }

    /**
     * Gets the value of the powerfocus property.
     * 
     * @return
     *     possible object is
     *     {@link Powerfocus }
     *     
     */
    public Powerfocus getPowerfocus() {
        return powerfocus;
    }

    /**
     * Sets the value of the powerfocus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Powerfocus }
     *     
     */
    public void setPowerfocus(Powerfocus value) {
        this.powerfocus = value;
    }

    /**
     * Gets the value of the powermode property.
     * 
     * @return
     *     possible object is
     *     {@link Powermode }
     *     
     */
    public Powermode getPowermode() {
        return powermode;
    }

    /**
     * Sets the value of the powermode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Powermode }
     *     
     */
    public void setPowermode(Powermode value) {
        this.powermode = value;
    }

    /**
     * Gets the value of the powers property.
     * 
     * @return
     *     possible object is
     *     {@link Powers }
     *     
     */
    public Powers getPowers() {
        return powers;
    }

    /**
     * Sets the value of the powers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Powers }
     *     
     */
    public void setPowers(Powers value) {
        this.powers = value;
    }

    /**
     * Gets the value of the powershow property.
     * 
     * @return
     *     possible object is
     *     {@link Powershow }
     *     
     */
    public Powershow getPowershow() {
        return powershow;
    }

    /**
     * Sets the value of the powershow property.
     * 
     * @param value
     *     allowed object is
     *     {@link Powershow }
     *     
     */
    public void setPowershow(Powershow value) {
        this.powershow = value;
    }

    /**
     * Gets the value of the proficiencyarmor property.
     * 
     * @return
     *     possible object is
     *     {@link Proficiencyarmor }
     *     
     */
    public Proficiencyarmor getProficiencyarmor() {
        return proficiencyarmor;
    }

    /**
     * Sets the value of the proficiencyarmor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Proficiencyarmor }
     *     
     */
    public void setProficiencyarmor(Proficiencyarmor value) {
        this.proficiencyarmor = value;
    }

    /**
     * Gets the value of the proficiencyweapon property.
     * 
     * @return
     *     possible object is
     *     {@link Proficiencyweapon }
     *     
     */
    public Proficiencyweapon getProficiencyweapon() {
        return proficiencyweapon;
    }

    /**
     * Sets the value of the proficiencyweapon property.
     * 
     * @param value
     *     allowed object is
     *     {@link Proficiencyweapon }
     *     
     */
    public void setProficiencyweapon(Proficiencyweapon value) {
        this.proficiencyweapon = value;
    }

    /**
     * Gets the value of the race property.
     * 
     * @return
     *     possible object is
     *     {@link Race }
     *     
     */
    public Race getRace() {
        return race;
    }

    /**
     * Sets the value of the race property.
     * 
     * @param value
     *     allowed object is
     *     {@link Race }
     *     
     */
    public void setRace(Race value) {
        this.race = value;
    }

    /**
     * Gets the value of the skilllist property.
     * 
     * @return
     *     possible object is
     *     {@link Skilllist }
     *     
     */
    public Skilllist getSkilllist() {
        return skilllist;
    }

    /**
     * Sets the value of the skilllist property.
     * 
     * @param value
     *     allowed object is
     *     {@link Skilllist }
     *     
     */
    public void setSkilllist(Skilllist value) {
        this.skilllist = value;
    }

    /**
     * Gets the value of the specialabilitylist property.
     * 
     * @return
     *     possible object is
     *     {@link Specialabilitylist }
     *     
     */
    public Specialabilitylist getSpecialabilitylist() {
        return specialabilitylist;
    }

    /**
     * Sets the value of the specialabilitylist property.
     * 
     * @param value
     *     allowed object is
     *     {@link Specialabilitylist }
     *     
     */
    public void setSpecialabilitylist(Specialabilitylist value) {
        this.specialabilitylist = value;
    }

    /**
     * Gets the value of the speed property.
     * 
     * @return
     *     possible object is
     *     {@link Speed }
     *     
     */
    public Speed getSpeed() {
        return speed;
    }

    /**
     * Sets the value of the speed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Speed }
     *     
     */
    public void setSpeed(Speed value) {
        this.speed = value;
    }

    /**
     * Gets the value of the weaponlist property.
     * 
     * @return
     *     possible object is
     *     {@link Weaponlist }
     *     
     */
    public Weaponlist getWeaponlist() {
        return weaponlist;
    }

    /**
     * Sets the value of the weaponlist property.
     * 
     * @param value
     *     allowed object is
     *     {@link Weaponlist }
     *     
     */
    public void setWeaponlist(Weaponlist value) {
        this.weaponlist = value;
    }

    /**
     * Gets the value of the portrait property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPortrait() {
        return portrait;
    }

    /**
     * Sets the value of the portrait property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPortrait(String value) {
        this.portrait = value;
    }

}
