//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.10 at 10:15:41 PM EDT 
//


package net.edmacdonald.fantasyGrounds.character.fourthEdition.jpg;

import net.edmacdonald.fantasyGrounds.character.fourthEdition.jpg.Amount;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}slot1"/>
 *         &lt;element ref="{}slot2"/>
 *         &lt;element ref="{}slot3"/>
 *         &lt;element ref="{}slot4"/>
 *         &lt;element ref="{}slot5"/>
 *         &lt;element ref="{}slot6"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "slot1",
    "slot2",
    "slot3",
    "slot4",
    "slot5",
    "slot6"
})
@XmlRootElement(name = "coins")
public class Coins {

    @XmlElement(required = true)
    protected Amount slot1;
    @XmlElement(required = true)
    protected Amount slot2;
    @XmlElement(required = true)
    protected Amount slot3;
    @XmlElement(required = true)
    protected Amount slot4;
    @XmlElement(required = true)
    protected Amount slot5;
    @XmlElement(required = true)
    protected Amount slot6;

    /**
     * Gets the value of the slot1 property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getSlot1() {
        return slot1;
    }

    /**
     * Sets the value of the slot1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setSlot1(Amount value) {
        this.slot1 = value;
    }

    /**
     * Gets the value of the slot2 property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getSlot2() {
        return slot2;
    }

    /**
     * Sets the value of the slot2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setSlot2(Amount value) {
        this.slot2 = value;
    }

    /**
     * Gets the value of the slot3 property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getSlot3() {
        return slot3;
    }

    /**
     * Sets the value of the slot3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setSlot3(Amount value) {
        this.slot3 = value;
    }

    /**
     * Gets the value of the slot4 property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getSlot4() {
        return slot4;
    }

    /**
     * Sets the value of the slot4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setSlot4(Amount value) {
        this.slot4 = value;
    }

    /**
     * Gets the value of the slot5 property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getSlot5() {
        return slot5;
    }

    /**
     * Sets the value of the slot5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setSlot5(Amount value) {
        this.slot5 = value;
    }

    /**
     * Gets the value of the slot6 property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getSlot6() {
        return slot6;
    }

    /**
     * Sets the value of the slot6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setSlot6(Amount value) {
        this.slot6 = value;
    }

}
