//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.10 at 10:15:41 PM EDT 
//


package net.edmacdonald.fantasyGrounds.character.fourthEdition.jpg;

import net.edmacdonald.fantasyGrounds.character.fourthEdition.jpg.Action;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice minOccurs="0">
 *           &lt;sequence>
 *             &lt;element ref="{}attackstatmodifier"/>
 *             &lt;element ref="{}damagebasicdice"/>
 *           &lt;/sequence>
 *           &lt;sequence>
 *             &lt;element ref="{}action"/>
 *             &lt;element ref="{}attacks"/>
 *             &lt;element ref="{}effects"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *         &lt;element ref="{}damagestat" minOccurs="0"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element ref="{}damagestatmodifier"/>
 *           &lt;element ref="{}damagetype"/>
 *           &lt;element ref="{}damageweaponmult"/>
 *           &lt;element ref="{}focus"/>
 *         &lt;/sequence>
 *         &lt;sequence minOccurs="0">
 *           &lt;element ref="{}effectsavemod"/>
 *           &lt;element ref="{}expiration"/>
 *         &lt;/sequence>
 *         &lt;choice minOccurs="0">
 *           &lt;element ref="{}keywords"/>
 *           &lt;sequence>
 *             &lt;element ref="{}carried"/>
 *             &lt;element ref="{}count"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *         &lt;element ref="{}classskill" minOccurs="0"/>
 *         &lt;element ref="{}label" minOccurs="0"/>
 *         &lt;element ref="{}misc" minOccurs="0"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element ref="{}attackdef"/>
 *           &lt;element ref="{}bonus"/>
 *           &lt;element ref="{}criticalbonus"/>
 *           &lt;element ref="{}criticaldice"/>
 *           &lt;element ref="{}damagebonus"/>
 *           &lt;element ref="{}damagedice"/>
 *           &lt;element ref="{}maxammo"/>
 *         &lt;/sequence>
 *         &lt;element ref="{}name" minOccurs="0"/>
 *         &lt;element ref="{}order" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element ref="{}rangeincrement"/>
 *           &lt;sequence>
 *             &lt;element ref="{}prepared"/>
 *             &lt;element ref="{}range"/>
 *             &lt;element ref="{}recharge"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *         &lt;element ref="{}shortcut" minOccurs="0"/>
 *         &lt;element ref="{}showonminisheet" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element ref="{}type"/>
 *           &lt;element ref="{}weight"/>
 *           &lt;sequence>
 *             &lt;element ref="{}shortdescription"/>
 *             &lt;element ref="{}source"/>
 *             &lt;element ref="{}used"/>
 *           &lt;/sequence>
 *           &lt;sequence>
 *             &lt;element ref="{}statname"/>
 *             &lt;element ref="{}total"/>
 *             &lt;element ref="{}trained"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "attackstatmodifier",
    "damagebasicdice",
    "action",
    "attacks",
    "effects",
    "damagestat",
    "damagestatmodifier",
    "damagetype",
    "damageweaponmult",
    "focus",
    "effectsavemod",
    "expiration",
    "keywords",
    "carried",
    "count",
    "classskill",
    "label",
    "misc",
    "attackdef",
    "bonus",
    "criticalbonus",
    "criticaldice",
    "damagebonus",
    "damagedice",
    "maxammo",
    "name",
    "order",
    "rangeincrement",
    "prepared",
    "range",
    "recharge",
    "shortcut",
    "showonminisheet",
    "type",
    "weight",
    "shortdescription",
    "source",
    "used",
    "statname",
    "total",
    "trained"
})
@XmlRootElement(name = "id-00002")
public class Id00002 {

    protected Attackstatmodifier attackstatmodifier;
    protected Damagebasicdice damagebasicdice;
    protected Action action;
    protected Attacks attacks;
    protected Effects effects;
    protected Damagestat damagestat;
    protected Damagestatmodifier damagestatmodifier;
    protected Damagetype damagetype;
    protected Damageweaponmult damageweaponmult;
    protected Focus focus;
    protected Effectsavemod effectsavemod;
    protected Expiration expiration;
    protected Keywords keywords;
    protected Carried carried;
    protected Count count;
    protected Classskill classskill;
    protected Label label;
    protected Misc misc;
    protected Attackdef attackdef;
    protected Bonus bonus;
    protected Criticalbonus criticalbonus;
    protected Criticaldice criticaldice;
    protected Damagebonus damagebonus;
    protected Damagedice damagedice;
    protected Maxammo maxammo;
    protected Name name;
    protected Order order;
    protected Rangeincrement rangeincrement;
    protected Prepared prepared;
    protected Range range;
    protected Recharge recharge;
    protected Shortcut shortcut;
    protected Showonminisheet showonminisheet;
    protected Type type;
    protected Weight weight;
    protected Shortdescription shortdescription;
    protected Source source;
    protected Used used;
    protected Statname statname;
    protected Total total;
    protected Trained trained;

    /**
     * Gets the value of the attackstatmodifier property.
     * 
     * @return
     *     possible object is
     *     {@link Attackstatmodifier }
     *     
     */
    public Attackstatmodifier getAttackstatmodifier() {
        return attackstatmodifier;
    }

    /**
     * Sets the value of the attackstatmodifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link Attackstatmodifier }
     *     
     */
    public void setAttackstatmodifier(Attackstatmodifier value) {
        this.attackstatmodifier = value;
    }

    /**
     * Gets the value of the damagebasicdice property.
     * 
     * @return
     *     possible object is
     *     {@link Damagebasicdice }
     *     
     */
    public Damagebasicdice getDamagebasicdice() {
        return damagebasicdice;
    }

    /**
     * Sets the value of the damagebasicdice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Damagebasicdice }
     *     
     */
    public void setDamagebasicdice(Damagebasicdice value) {
        this.damagebasicdice = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link Action }
     *     
     */
    public Action getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link Action }
     *     
     */
    public void setAction(Action value) {
        this.action = value;
    }

    /**
     * Gets the value of the attacks property.
     * 
     * @return
     *     possible object is
     *     {@link Attacks }
     *     
     */
    public Attacks getAttacks() {
        return attacks;
    }

    /**
     * Sets the value of the attacks property.
     * 
     * @param value
     *     allowed object is
     *     {@link Attacks }
     *     
     */
    public void setAttacks(Attacks value) {
        this.attacks = value;
    }

    /**
     * Gets the value of the effects property.
     * 
     * @return
     *     possible object is
     *     {@link Effects }
     *     
     */
    public Effects getEffects() {
        return effects;
    }

    /**
     * Sets the value of the effects property.
     * 
     * @param value
     *     allowed object is
     *     {@link Effects }
     *     
     */
    public void setEffects(Effects value) {
        this.effects = value;
    }

    /**
     * Gets the value of the damagestat property.
     * 
     * @return
     *     possible object is
     *     {@link Damagestat }
     *     
     */
    public Damagestat getDamagestat() {
        return damagestat;
    }

    /**
     * Sets the value of the damagestat property.
     * 
     * @param value
     *     allowed object is
     *     {@link Damagestat }
     *     
     */
    public void setDamagestat(Damagestat value) {
        this.damagestat = value;
    }

    /**
     * Gets the value of the damagestatmodifier property.
     * 
     * @return
     *     possible object is
     *     {@link Damagestatmodifier }
     *     
     */
    public Damagestatmodifier getDamagestatmodifier() {
        return damagestatmodifier;
    }

    /**
     * Sets the value of the damagestatmodifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link Damagestatmodifier }
     *     
     */
    public void setDamagestatmodifier(Damagestatmodifier value) {
        this.damagestatmodifier = value;
    }

    /**
     * Gets the value of the damagetype property.
     * 
     * @return
     *     possible object is
     *     {@link Damagetype }
     *     
     */
    public Damagetype getDamagetype() {
        return damagetype;
    }

    /**
     * Sets the value of the damagetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link Damagetype }
     *     
     */
    public void setDamagetype(Damagetype value) {
        this.damagetype = value;
    }

    /**
     * Gets the value of the damageweaponmult property.
     * 
     * @return
     *     possible object is
     *     {@link Damageweaponmult }
     *     
     */
    public Damageweaponmult getDamageweaponmult() {
        return damageweaponmult;
    }

    /**
     * Sets the value of the damageweaponmult property.
     * 
     * @param value
     *     allowed object is
     *     {@link Damageweaponmult }
     *     
     */
    public void setDamageweaponmult(Damageweaponmult value) {
        this.damageweaponmult = value;
    }

    /**
     * Gets the value of the focus property.
     * 
     * @return
     *     possible object is
     *     {@link Focus }
     *     
     */
    public Focus getFocus() {
        return focus;
    }

    /**
     * Sets the value of the focus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Focus }
     *     
     */
    public void setFocus(Focus value) {
        this.focus = value;
    }

    /**
     * Gets the value of the effectsavemod property.
     * 
     * @return
     *     possible object is
     *     {@link Effectsavemod }
     *     
     */
    public Effectsavemod getEffectsavemod() {
        return effectsavemod;
    }

    /**
     * Sets the value of the effectsavemod property.
     * 
     * @param value
     *     allowed object is
     *     {@link Effectsavemod }
     *     
     */
    public void setEffectsavemod(Effectsavemod value) {
        this.effectsavemod = value;
    }

    /**
     * Gets the value of the expiration property.
     * 
     * @return
     *     possible object is
     *     {@link Expiration }
     *     
     */
    public Expiration getExpiration() {
        return expiration;
    }

    /**
     * Sets the value of the expiration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Expiration }
     *     
     */
    public void setExpiration(Expiration value) {
        this.expiration = value;
    }

    /**
     * Gets the value of the keywords property.
     * 
     * @return
     *     possible object is
     *     {@link Keywords }
     *     
     */
    public Keywords getKeywords() {
        return keywords;
    }

    /**
     * Sets the value of the keywords property.
     * 
     * @param value
     *     allowed object is
     *     {@link Keywords }
     *     
     */
    public void setKeywords(Keywords value) {
        this.keywords = value;
    }

    /**
     * Gets the value of the carried property.
     * 
     * @return
     *     possible object is
     *     {@link Carried }
     *     
     */
    public Carried getCarried() {
        return carried;
    }

    /**
     * Sets the value of the carried property.
     * 
     * @param value
     *     allowed object is
     *     {@link Carried }
     *     
     */
    public void setCarried(Carried value) {
        this.carried = value;
    }

    /**
     * Gets the value of the count property.
     * 
     * @return
     *     possible object is
     *     {@link Count }
     *     
     */
    public Count getCount() {
        return count;
    }

    /**
     * Sets the value of the count property.
     * 
     * @param value
     *     allowed object is
     *     {@link Count }
     *     
     */
    public void setCount(Count value) {
        this.count = value;
    }

    /**
     * Gets the value of the classskill property.
     * 
     * @return
     *     possible object is
     *     {@link Classskill }
     *     
     */
    public Classskill getClassskill() {
        return classskill;
    }

    /**
     * Sets the value of the classskill property.
     * 
     * @param value
     *     allowed object is
     *     {@link Classskill }
     *     
     */
    public void setClassskill(Classskill value) {
        this.classskill = value;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link Label }
     *     
     */
    public Label getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link Label }
     *     
     */
    public void setLabel(Label value) {
        this.label = value;
    }

    /**
     * Gets the value of the misc property.
     * 
     * @return
     *     possible object is
     *     {@link Misc }
     *     
     */
    public Misc getMisc() {
        return misc;
    }

    /**
     * Sets the value of the misc property.
     * 
     * @param value
     *     allowed object is
     *     {@link Misc }
     *     
     */
    public void setMisc(Misc value) {
        this.misc = value;
    }

    /**
     * Gets the value of the attackdef property.
     * 
     * @return
     *     possible object is
     *     {@link Attackdef }
     *     
     */
    public Attackdef getAttackdef() {
        return attackdef;
    }

    /**
     * Sets the value of the attackdef property.
     * 
     * @param value
     *     allowed object is
     *     {@link Attackdef }
     *     
     */
    public void setAttackdef(Attackdef value) {
        this.attackdef = value;
    }

    /**
     * Gets the value of the bonus property.
     * 
     * @return
     *     possible object is
     *     {@link Bonus }
     *     
     */
    public Bonus getBonus() {
        return bonus;
    }

    /**
     * Sets the value of the bonus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Bonus }
     *     
     */
    public void setBonus(Bonus value) {
        this.bonus = value;
    }

    /**
     * Gets the value of the criticalbonus property.
     * 
     * @return
     *     possible object is
     *     {@link Criticalbonus }
     *     
     */
    public Criticalbonus getCriticalbonus() {
        return criticalbonus;
    }

    /**
     * Sets the value of the criticalbonus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Criticalbonus }
     *     
     */
    public void setCriticalbonus(Criticalbonus value) {
        this.criticalbonus = value;
    }

    /**
     * Gets the value of the criticaldice property.
     * 
     * @return
     *     possible object is
     *     {@link Criticaldice }
     *     
     */
    public Criticaldice getCriticaldice() {
        return criticaldice;
    }

    /**
     * Sets the value of the criticaldice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Criticaldice }
     *     
     */
    public void setCriticaldice(Criticaldice value) {
        this.criticaldice = value;
    }

    /**
     * Gets the value of the damagebonus property.
     * 
     * @return
     *     possible object is
     *     {@link Damagebonus }
     *     
     */
    public Damagebonus getDamagebonus() {
        return damagebonus;
    }

    /**
     * Sets the value of the damagebonus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Damagebonus }
     *     
     */
    public void setDamagebonus(Damagebonus value) {
        this.damagebonus = value;
    }

    /**
     * Gets the value of the damagedice property.
     * 
     * @return
     *     possible object is
     *     {@link Damagedice }
     *     
     */
    public Damagedice getDamagedice() {
        return damagedice;
    }

    /**
     * Sets the value of the damagedice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Damagedice }
     *     
     */
    public void setDamagedice(Damagedice value) {
        this.damagedice = value;
    }

    /**
     * Gets the value of the maxammo property.
     * 
     * @return
     *     possible object is
     *     {@link Maxammo }
     *     
     */
    public Maxammo getMaxammo() {
        return maxammo;
    }

    /**
     * Sets the value of the maxammo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Maxammo }
     *     
     */
    public void setMaxammo(Maxammo value) {
        this.maxammo = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link Name }
     *     
     */
    public Name getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link Name }
     *     
     */
    public void setName(Name value) {
        this.name = value;
    }

    /**
     * Gets the value of the order property.
     * 
     * @return
     *     possible object is
     *     {@link Order }
     *     
     */
    public Order getOrder() {
        return order;
    }

    /**
     * Sets the value of the order property.
     * 
     * @param value
     *     allowed object is
     *     {@link Order }
     *     
     */
    public void setOrder(Order value) {
        this.order = value;
    }

    /**
     * Gets the value of the rangeincrement property.
     * 
     * @return
     *     possible object is
     *     {@link Rangeincrement }
     *     
     */
    public Rangeincrement getRangeincrement() {
        return rangeincrement;
    }

    /**
     * Sets the value of the rangeincrement property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rangeincrement }
     *     
     */
    public void setRangeincrement(Rangeincrement value) {
        this.rangeincrement = value;
    }

    /**
     * Gets the value of the prepared property.
     * 
     * @return
     *     possible object is
     *     {@link Prepared }
     *     
     */
    public Prepared getPrepared() {
        return prepared;
    }

    /**
     * Sets the value of the prepared property.
     * 
     * @param value
     *     allowed object is
     *     {@link Prepared }
     *     
     */
    public void setPrepared(Prepared value) {
        this.prepared = value;
    }

    /**
     * Gets the value of the range property.
     * 
     * @return
     *     possible object is
     *     {@link Range }
     *     
     */
    public Range getRange() {
        return range;
    }

    /**
     * Sets the value of the range property.
     * 
     * @param value
     *     allowed object is
     *     {@link Range }
     *     
     */
    public void setRange(Range value) {
        this.range = value;
    }

    /**
     * Gets the value of the recharge property.
     * 
     * @return
     *     possible object is
     *     {@link Recharge }
     *     
     */
    public Recharge getRecharge() {
        return recharge;
    }

    /**
     * Sets the value of the recharge property.
     * 
     * @param value
     *     allowed object is
     *     {@link Recharge }
     *     
     */
    public void setRecharge(Recharge value) {
        this.recharge = value;
    }

    /**
     * Gets the value of the shortcut property.
     * 
     * @return
     *     possible object is
     *     {@link Shortcut }
     *     
     */
    public Shortcut getShortcut() {
        return shortcut;
    }

    /**
     * Sets the value of the shortcut property.
     * 
     * @param value
     *     allowed object is
     *     {@link Shortcut }
     *     
     */
    public void setShortcut(Shortcut value) {
        this.shortcut = value;
    }

    /**
     * Gets the value of the showonminisheet property.
     * 
     * @return
     *     possible object is
     *     {@link Showonminisheet }
     *     
     */
    public Showonminisheet getShowonminisheet() {
        return showonminisheet;
    }

    /**
     * Sets the value of the showonminisheet property.
     * 
     * @param value
     *     allowed object is
     *     {@link Showonminisheet }
     *     
     */
    public void setShowonminisheet(Showonminisheet value) {
        this.showonminisheet = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link Type }
     *     
     */
    public Type getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link Type }
     *     
     */
    public void setType(Type value) {
        this.type = value;
    }

    /**
     * Gets the value of the weight property.
     * 
     * @return
     *     possible object is
     *     {@link Weight }
     *     
     */
    public Weight getWeight() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Weight }
     *     
     */
    public void setWeight(Weight value) {
        this.weight = value;
    }

    /**
     * Gets the value of the shortdescription property.
     * 
     * @return
     *     possible object is
     *     {@link Shortdescription }
     *     
     */
    public Shortdescription getShortdescription() {
        return shortdescription;
    }

    /**
     * Sets the value of the shortdescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link Shortdescription }
     *     
     */
    public void setShortdescription(Shortdescription value) {
        this.shortdescription = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link Source }
     *     
     */
    public Source getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link Source }
     *     
     */
    public void setSource(Source value) {
        this.source = value;
    }

    /**
     * Gets the value of the used property.
     * 
     * @return
     *     possible object is
     *     {@link Used }
     *     
     */
    public Used getUsed() {
        return used;
    }

    /**
     * Sets the value of the used property.
     * 
     * @param value
     *     allowed object is
     *     {@link Used }
     *     
     */
    public void setUsed(Used value) {
        this.used = value;
    }

    /**
     * Gets the value of the statname property.
     * 
     * @return
     *     possible object is
     *     {@link Statname }
     *     
     */
    public Statname getStatname() {
        return statname;
    }

    /**
     * Sets the value of the statname property.
     * 
     * @param value
     *     allowed object is
     *     {@link Statname }
     *     
     */
    public void setStatname(Statname value) {
        this.statname = value;
    }

    /**
     * Gets the value of the total property.
     * 
     * @return
     *     possible object is
     *     {@link Total }
     *     
     */
    public Total getTotal() {
        return total;
    }

    /**
     * Sets the value of the total property.
     * 
     * @param value
     *     allowed object is
     *     {@link Total }
     *     
     */
    public void setTotal(Total value) {
        this.total = value;
    }

    /**
     * Gets the value of the trained property.
     * 
     * @return
     *     possible object is
     *     {@link Trained }
     *     
     */
    public Trained getTrained() {
        return trained;
    }

    /**
     * Sets the value of the trained property.
     * 
     * @param value
     *     allowed object is
     *     {@link Trained }
     *     
     */
    public void setTrained(Trained value) {
        this.trained = value;
    }

}
