//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.10 at 10:15:41 PM EDT 
//


package net.edmacdonald.fantasyGrounds.character.fourthEdition.jpg;

import net.edmacdonald.fantasyGrounds.character.fourthEdition.jpg.A0Situational;
import net.edmacdonald.fantasyGrounds.character.fourthEdition.jpg.A11Atwillspecial;
import net.edmacdonald.fantasyGrounds.character.fourthEdition.jpg.A1Atwill;
import net.edmacdonald.fantasyGrounds.character.fourthEdition.jpg.A2Cantrip;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{}id-001"/>
 *         &lt;sequence>
 *           &lt;element ref="{}a0-situational"/>
 *           &lt;element ref="{}a1-atwill"/>
 *           &lt;element ref="{}a11-atwillspecial"/>
 *           &lt;element ref="{}a2-cantrip"/>
 *           &lt;element ref="{}b1-encounter"/>
 *           &lt;element ref="{}b11-encounterspecial"/>
 *           &lt;element ref="{}b2-channeldivinity"/>
 *           &lt;element ref="{}c-daily"/>
 *           &lt;element ref="{}d-utility"/>
 *           &lt;element ref="{}e-itemdaily"/>
 *         &lt;/sequence>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id001",
    "a0Situational",
    "a1Atwill",
    "a11Atwillspecial",
    "a2Cantrip",
    "b1Encounter",
    "b11Encounterspecial",
    "b2Channeldivinity",
    "cDaily",
    "dUtility",
    "eItemdaily"
})
@XmlRootElement(name = "powers")
public class Powers {

    @XmlElement(name = "id-001")
    protected Id001 id001;
    @XmlElement(name = "a0-situational")
    protected A0Situational a0Situational;
    @XmlElement(name = "a1-atwill")
    protected A1Atwill a1Atwill;
    @XmlElement(name = "a11-atwillspecial")
    protected A11Atwillspecial a11Atwillspecial;
    @XmlElement(name = "a2-cantrip")
    protected A2Cantrip a2Cantrip;
    @XmlElement(name = "b1-encounter")
    protected B1Encounter b1Encounter;
    @XmlElement(name = "b11-encounterspecial")
    protected B11Encounterspecial b11Encounterspecial;
    @XmlElement(name = "b2-channeldivinity")
    protected B2Channeldivinity b2Channeldivinity;
    @XmlElement(name = "c-daily")
    protected CDaily cDaily;
    @XmlElement(name = "d-utility")
    protected DUtility dUtility;
    @XmlElement(name = "e-itemdaily")
    protected EItemdaily eItemdaily;

    /**
     * Gets the value of the id001 property.
     * 
     * @return
     *     possible object is
     *     {@link Id001 }
     *     
     */
    public Id001 getId001() {
        return id001;
    }

    /**
     * Sets the value of the id001 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Id001 }
     *     
     */
    public void setId001(Id001 value) {
        this.id001 = value;
    }

    /**
     * Gets the value of the a0Situational property.
     * 
     * @return
     *     possible object is
     *     {@link A0Situational }
     *     
     */
    public A0Situational getA0Situational() {
        return a0Situational;
    }

    /**
     * Sets the value of the a0Situational property.
     * 
     * @param value
     *     allowed object is
     *     {@link A0Situational }
     *     
     */
    public void setA0Situational(A0Situational value) {
        this.a0Situational = value;
    }

    /**
     * Gets the value of the a1Atwill property.
     * 
     * @return
     *     possible object is
     *     {@link A1Atwill }
     *     
     */
    public A1Atwill getA1Atwill() {
        return a1Atwill;
    }

    /**
     * Sets the value of the a1Atwill property.
     * 
     * @param value
     *     allowed object is
     *     {@link A1Atwill }
     *     
     */
    public void setA1Atwill(A1Atwill value) {
        this.a1Atwill = value;
    }

    /**
     * Gets the value of the a11Atwillspecial property.
     * 
     * @return
     *     possible object is
     *     {@link A11Atwillspecial }
     *     
     */
    public A11Atwillspecial getA11Atwillspecial() {
        return a11Atwillspecial;
    }

    /**
     * Sets the value of the a11Atwillspecial property.
     * 
     * @param value
     *     allowed object is
     *     {@link A11Atwillspecial }
     *     
     */
    public void setA11Atwillspecial(A11Atwillspecial value) {
        this.a11Atwillspecial = value;
    }

    /**
     * Gets the value of the a2Cantrip property.
     * 
     * @return
     *     possible object is
     *     {@link net.edmacdonald.fantasyGrounds.character.fourthEdition.jpg.A2Cantrip }
     *     
     */
    public A2Cantrip getA2Cantrip() {
        return a2Cantrip;
    }

    /**
     * Sets the value of the a2Cantrip property.
     * 
     * @param value
     *     allowed object is
     *     {@link net.edmacdonald.fantasyGrounds.character.fourthEdition.jpg.A2Cantrip }
     *     
     */
    public void setA2Cantrip(A2Cantrip value) {
        this.a2Cantrip = value;
    }

    /**
     * Gets the value of the b1Encounter property.
     * 
     * @return
     *     possible object is
     *     {@link B1Encounter }
     *     
     */
    public B1Encounter getB1Encounter() {
        return b1Encounter;
    }

    /**
     * Sets the value of the b1Encounter property.
     * 
     * @param value
     *     allowed object is
     *     {@link B1Encounter }
     *     
     */
    public void setB1Encounter(B1Encounter value) {
        this.b1Encounter = value;
    }

    /**
     * Gets the value of the b11Encounterspecial property.
     * 
     * @return
     *     possible object is
     *     {@link B11Encounterspecial }
     *     
     */
    public B11Encounterspecial getB11Encounterspecial() {
        return b11Encounterspecial;
    }

    /**
     * Sets the value of the b11Encounterspecial property.
     * 
     * @param value
     *     allowed object is
     *     {@link B11Encounterspecial }
     *     
     */
    public void setB11Encounterspecial(B11Encounterspecial value) {
        this.b11Encounterspecial = value;
    }

    /**
     * Gets the value of the b2Channeldivinity property.
     * 
     * @return
     *     possible object is
     *     {@link B2Channeldivinity }
     *     
     */
    public B2Channeldivinity getB2Channeldivinity() {
        return b2Channeldivinity;
    }

    /**
     * Sets the value of the b2Channeldivinity property.
     * 
     * @param value
     *     allowed object is
     *     {@link B2Channeldivinity }
     *     
     */
    public void setB2Channeldivinity(B2Channeldivinity value) {
        this.b2Channeldivinity = value;
    }

    /**
     * Gets the value of the cDaily property.
     * 
     * @return
     *     possible object is
     *     {@link CDaily }
     *     
     */
    public CDaily getCDaily() {
        return cDaily;
    }

    /**
     * Sets the value of the cDaily property.
     * 
     * @param value
     *     allowed object is
     *     {@link CDaily }
     *     
     */
    public void setCDaily(CDaily value) {
        this.cDaily = value;
    }

    /**
     * Gets the value of the dUtility property.
     * 
     * @return
     *     possible object is
     *     {@link DUtility }
     *     
     */
    public DUtility getDUtility() {
        return dUtility;
    }

    /**
     * Sets the value of the dUtility property.
     * 
     * @param value
     *     allowed object is
     *     {@link DUtility }
     *     
     */
    public void setDUtility(DUtility value) {
        this.dUtility = value;
    }

    /**
     * Gets the value of the eItemdaily property.
     * 
     * @return
     *     possible object is
     *     {@link EItemdaily }
     *     
     */
    public EItemdaily getEItemdaily() {
        return eItemdaily;
    }

    /**
     * Sets the value of the eItemdaily property.
     * 
     * @param value
     *     allowed object is
     *     {@link EItemdaily }
     *     
     */
    public void setEItemdaily(EItemdaily value) {
        this.eItemdaily = value;
    }

}
