//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.10 at 10:15:41 PM EDT 
//


package net.edmacdonald.fantasyGrounds.character.fourthEdition.jpg;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}id-00001"/>
 *         &lt;element ref="{}id-00002"/>
 *         &lt;element ref="{}id-00003"/>
 *         &lt;element ref="{}id-00004"/>
 *         &lt;element ref="{}id-00005"/>
 *         &lt;element ref="{}id-00006"/>
 *         &lt;element ref="{}id-00007"/>
 *         &lt;element ref="{}id-00008"/>
 *         &lt;element ref="{}id-00009"/>
 *         &lt;element ref="{}id-00010"/>
 *         &lt;element ref="{}id-00011"/>
 *         &lt;element ref="{}id-00012"/>
 *         &lt;element ref="{}id-00013"/>
 *         &lt;element ref="{}id-00014"/>
 *         &lt;element ref="{}id-00015"/>
 *         &lt;element ref="{}id-00016"/>
 *         &lt;element ref="{}id-00017"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id00001",
    "id00002",
    "id00003",
    "id00004",
    "id00005",
    "id00006",
    "id00007",
    "id00008",
    "id00009",
    "id00010",
    "id00011",
    "id00012",
    "id00013",
    "id00014",
    "id00015",
    "id00016",
    "id00017"
})
@XmlRootElement(name = "skilllist")
public class Skilllist {

    @XmlElement(name = "id-00001", required = true)
    protected Id00001 id00001;
    @XmlElement(name = "id-00002", required = true)
    protected Id00002 id00002;
    @XmlElement(name = "id-00003", required = true)
    protected Id00003 id00003;
    @XmlElement(name = "id-00004", required = true)
    protected Id00004 id00004;
    @XmlElement(name = "id-00005", required = true)
    protected Id00005 id00005;
    @XmlElement(name = "id-00006", required = true)
    protected Id00006 id00006;
    @XmlElement(name = "id-00007", required = true)
    protected Id00007 id00007;
    @XmlElement(name = "id-00008", required = true)
    protected Id00008 id00008;
    @XmlElement(name = "id-00009", required = true)
    protected Id00009 id00009;
    @XmlElement(name = "id-00010", required = true)
    protected Id00010 id00010;
    @XmlElement(name = "id-00011", required = true)
    protected Id00011 id00011;
    @XmlElement(name = "id-00012", required = true)
    protected Id00012 id00012;
    @XmlElement(name = "id-00013", required = true)
    protected Id00013 id00013;
    @XmlElement(name = "id-00014", required = true)
    protected Id00014 id00014;
    @XmlElement(name = "id-00015", required = true)
    protected Id00015 id00015;
    @XmlElement(name = "id-00016", required = true)
    protected Id00016 id00016;
    @XmlElement(name = "id-00017", required = true)
    protected Id00017 id00017;

    /**
     * Gets the value of the id00001 property.
     * 
     * @return
     *     possible object is
     *     {@link Id00001 }
     *     
     */
    public Id00001 getId00001() {
        return id00001;
    }

    /**
     * Sets the value of the id00001 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Id00001 }
     *     
     */
    public void setId00001(Id00001 value) {
        this.id00001 = value;
    }

    /**
     * Gets the value of the id00002 property.
     * 
     * @return
     *     possible object is
     *     {@link Id00002 }
     *     
     */
    public Id00002 getId00002() {
        return id00002;
    }

    /**
     * Sets the value of the id00002 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Id00002 }
     *     
     */
    public void setId00002(Id00002 value) {
        this.id00002 = value;
    }

    /**
     * Gets the value of the id00003 property.
     * 
     * @return
     *     possible object is
     *     {@link Id00003 }
     *     
     */
    public Id00003 getId00003() {
        return id00003;
    }

    /**
     * Sets the value of the id00003 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Id00003 }
     *     
     */
    public void setId00003(Id00003 value) {
        this.id00003 = value;
    }

    /**
     * Gets the value of the id00004 property.
     * 
     * @return
     *     possible object is
     *     {@link Id00004 }
     *     
     */
    public Id00004 getId00004() {
        return id00004;
    }

    /**
     * Sets the value of the id00004 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Id00004 }
     *     
     */
    public void setId00004(Id00004 value) {
        this.id00004 = value;
    }

    /**
     * Gets the value of the id00005 property.
     * 
     * @return
     *     possible object is
     *     {@link Id00005 }
     *     
     */
    public Id00005 getId00005() {
        return id00005;
    }

    /**
     * Sets the value of the id00005 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Id00005 }
     *     
     */
    public void setId00005(Id00005 value) {
        this.id00005 = value;
    }

    /**
     * Gets the value of the id00006 property.
     * 
     * @return
     *     possible object is
     *     {@link Id00006 }
     *     
     */
    public Id00006 getId00006() {
        return id00006;
    }

    /**
     * Sets the value of the id00006 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Id00006 }
     *     
     */
    public void setId00006(Id00006 value) {
        this.id00006 = value;
    }

    /**
     * Gets the value of the id00007 property.
     * 
     * @return
     *     possible object is
     *     {@link Id00007 }
     *     
     */
    public Id00007 getId00007() {
        return id00007;
    }

    /**
     * Sets the value of the id00007 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Id00007 }
     *     
     */
    public void setId00007(Id00007 value) {
        this.id00007 = value;
    }

    /**
     * Gets the value of the id00008 property.
     * 
     * @return
     *     possible object is
     *     {@link Id00008 }
     *     
     */
    public Id00008 getId00008() {
        return id00008;
    }

    /**
     * Sets the value of the id00008 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Id00008 }
     *     
     */
    public void setId00008(Id00008 value) {
        this.id00008 = value;
    }

    /**
     * Gets the value of the id00009 property.
     * 
     * @return
     *     possible object is
     *     {@link Id00009 }
     *     
     */
    public Id00009 getId00009() {
        return id00009;
    }

    /**
     * Sets the value of the id00009 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Id00009 }
     *     
     */
    public void setId00009(Id00009 value) {
        this.id00009 = value;
    }

    /**
     * Gets the value of the id00010 property.
     * 
     * @return
     *     possible object is
     *     {@link Id00010 }
     *     
     */
    public Id00010 getId00010() {
        return id00010;
    }

    /**
     * Sets the value of the id00010 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Id00010 }
     *     
     */
    public void setId00010(Id00010 value) {
        this.id00010 = value;
    }

    /**
     * Gets the value of the id00011 property.
     * 
     * @return
     *     possible object is
     *     {@link Id00011 }
     *     
     */
    public Id00011 getId00011() {
        return id00011;
    }

    /**
     * Sets the value of the id00011 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Id00011 }
     *     
     */
    public void setId00011(Id00011 value) {
        this.id00011 = value;
    }

    /**
     * Gets the value of the id00012 property.
     * 
     * @return
     *     possible object is
     *     {@link Id00012 }
     *     
     */
    public Id00012 getId00012() {
        return id00012;
    }

    /**
     * Sets the value of the id00012 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Id00012 }
     *     
     */
    public void setId00012(Id00012 value) {
        this.id00012 = value;
    }

    /**
     * Gets the value of the id00013 property.
     * 
     * @return
     *     possible object is
     *     {@link Id00013 }
     *     
     */
    public Id00013 getId00013() {
        return id00013;
    }

    /**
     * Sets the value of the id00013 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Id00013 }
     *     
     */
    public void setId00013(Id00013 value) {
        this.id00013 = value;
    }

    /**
     * Gets the value of the id00014 property.
     * 
     * @return
     *     possible object is
     *     {@link Id00014 }
     *     
     */
    public Id00014 getId00014() {
        return id00014;
    }

    /**
     * Sets the value of the id00014 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Id00014 }
     *     
     */
    public void setId00014(Id00014 value) {
        this.id00014 = value;
    }

    /**
     * Gets the value of the id00015 property.
     * 
     * @return
     *     possible object is
     *     {@link Id00015 }
     *     
     */
    public Id00015 getId00015() {
        return id00015;
    }

    /**
     * Sets the value of the id00015 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Id00015 }
     *     
     */
    public void setId00015(Id00015 value) {
        this.id00015 = value;
    }

    /**
     * Gets the value of the id00016 property.
     * 
     * @return
     *     possible object is
     *     {@link Id00016 }
     *     
     */
    public Id00016 getId00016() {
        return id00016;
    }

    /**
     * Sets the value of the id00016 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Id00016 }
     *     
     */
    public void setId00016(Id00016 value) {
        this.id00016 = value;
    }

    /**
     * Gets the value of the id00017 property.
     * 
     * @return
     *     possible object is
     *     {@link Id00017 }
     *     
     */
    public Id00017 getId00017() {
        return id00017;
    }

    /**
     * Sets the value of the id00017 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Id00017 }
     *     
     */
    public void setId00017(Id00017 value) {
        this.id00017 = value;
    }

}
