//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.10 at 10:15:41 PM EDT 
//


package net.edmacdonald.fantasyGrounds;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}charisma"/>
 *         &lt;element ref="{}constitution"/>
 *         &lt;element ref="{}dexterity"/>
 *         &lt;element ref="{}intelligence"/>
 *         &lt;element ref="{}strength"/>
 *         &lt;element ref="{}wisdom"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "charisma",
    "constitution",
    "dexterity",
    "intelligence",
    "strength",
    "wisdom"
})
@XmlRootElement(name = "abilities")
public class Abilities {

    @XmlElement(required = true)
    protected Charisma charisma;
    @XmlElement(required = true)
    protected Constitution constitution;
    @XmlElement(required = true)
    protected Dexterity dexterity;
    @XmlElement(required = true)
    protected Intelligence intelligence;
    @XmlElement(required = true)
    protected Strength strength;
    @XmlElement(required = true)
    protected Wisdom wisdom;

    /**
     * Gets the value of the charisma property.
     * 
     * @return
     *     possible object is
     *     {@link Charisma }
     *     
     */
    public Charisma getCharisma() {
        return charisma;
    }

    /**
     * Sets the value of the charisma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Charisma }
     *     
     */
    public void setCharisma(Charisma value) {
        this.charisma = value;
    }

    /**
     * Gets the value of the constitution property.
     * 
     * @return
     *     possible object is
     *     {@link Constitution }
     *     
     */
    public Constitution getConstitution() {
        return constitution;
    }

    /**
     * Sets the value of the constitution property.
     * 
     * @param value
     *     allowed object is
     *     {@link Constitution }
     *     
     */
    public void setConstitution(Constitution value) {
        this.constitution = value;
    }

    /**
     * Gets the value of the dexterity property.
     * 
     * @return
     *     possible object is
     *     {@link Dexterity }
     *     
     */
    public Dexterity getDexterity() {
        return dexterity;
    }

    /**
     * Sets the value of the dexterity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dexterity }
     *     
     */
    public void setDexterity(Dexterity value) {
        this.dexterity = value;
    }

    /**
     * Gets the value of the intelligence property.
     * 
     * @return
     *     possible object is
     *     {@link Intelligence }
     *     
     */
    public Intelligence getIntelligence() {
        return intelligence;
    }

    /**
     * Sets the value of the intelligence property.
     * 
     * @param value
     *     allowed object is
     *     {@link Intelligence }
     *     
     */
    public void setIntelligence(Intelligence value) {
        this.intelligence = value;
    }

    /**
     * Gets the value of the strength property.
     * 
     * @return
     *     possible object is
     *     {@link Strength }
     *     
     */
    public Strength getStrength() {
        return strength;
    }

    /**
     * Sets the value of the strength property.
     * 
     * @param value
     *     allowed object is
     *     {@link Strength }
     *     
     */
    public void setStrength(Strength value) {
        this.strength = value;
    }

    /**
     * Gets the value of the wisdom property.
     * 
     * @return
     *     possible object is
     *     {@link Wisdom }
     *     
     */
    public Wisdom getWisdom() {
        return wisdom;
    }

    /**
     * Sets the value of the wisdom property.
     * 
     * @param value
     *     allowed object is
     *     {@link Wisdom }
     *     
     */
    public void setWisdom(Wisdom value) {
        this.wisdom = value;
    }

}
