//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.10 at 10:15:41 PM EDT 
//


package net.edmacdonald.fantasyGrounds;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}bonus"/>
 *         &lt;element ref="{}bonusmodifier"/>
 *         &lt;element ref="{}check"/>
 *         &lt;element ref="{}score"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bonus",
    "bonusmodifier",
    "check",
    "score"
})
@XmlRootElement(name = "charisma")
public class Charisma {

    @XmlElement(required = true)
    protected Bonus bonus;
    @XmlElement(required = true)
    protected Bonusmodifier bonusmodifier;
    @XmlElement(required = true)
    protected Check check;
    @XmlElement(required = true)
    protected Score score;

    /**
     * Gets the value of the bonus property.
     * 
     * @return
     *     possible object is
     *     {@link Bonus }
     *     
     */
    public Bonus getBonus() {
        return bonus;
    }

    /**
     * Sets the value of the bonus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Bonus }
     *     
     */
    public void setBonus(Bonus value) {
        this.bonus = value;
    }

    /**
     * Gets the value of the bonusmodifier property.
     * 
     * @return
     *     possible object is
     *     {@link Bonusmodifier }
     *     
     */
    public Bonusmodifier getBonusmodifier() {
        return bonusmodifier;
    }

    /**
     * Sets the value of the bonusmodifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link Bonusmodifier }
     *     
     */
    public void setBonusmodifier(Bonusmodifier value) {
        this.bonusmodifier = value;
    }

    /**
     * Gets the value of the check property.
     * 
     * @return
     *     possible object is
     *     {@link Check }
     *     
     */
    public Check getCheck() {
        return check;
    }

    /**
     * Sets the value of the check property.
     * 
     * @param value
     *     allowed object is
     *     {@link Check }
     *     
     */
    public void setCheck(Check value) {
        this.check = value;
    }

    /**
     * Gets the value of the score property.
     * 
     * @return
     *     possible object is
     *     {@link Score }
     *     
     */
    public Score getScore() {
        return score;
    }

    /**
     * Sets the value of the score property.
     * 
     * @param value
     *     allowed object is
     *     {@link Score }
     *     
     */
    public void setScore(Score value) {
        this.score = value;
    }

}
