//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.10 at 10:15:41 PM EDT 
//


package net.edmacdonald.fantasyGrounds;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}armorcheckpenalty"/>
 *         &lt;element ref="{}dragload"/>
 *         &lt;element ref="{}heavyarmor"/>
 *         &lt;element ref="{}heavyload"/>
 *         &lt;element ref="{}load"/>
 *         &lt;element ref="{}normalload"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "armorcheckpenalty",
    "dragload",
    "heavyarmor",
    "heavyload",
    "load",
    "normalload"
})
@XmlRootElement(name = "encumbrance")
public class Encumbrance {

    @XmlElement(required = true)
    protected Armorcheckpenalty armorcheckpenalty;
    @XmlElement(required = true)
    protected Dragload dragload;
    @XmlElement(required = true)
    protected Heavyarmor heavyarmor;
    @XmlElement(required = true)
    protected Heavyload heavyload;
    @XmlElement(required = true)
    protected Load load;
    @XmlElement(required = true)
    protected Normalload normalload;

    /**
     * Gets the value of the armorcheckpenalty property.
     * 
     * @return
     *     possible object is
     *     {@link Armorcheckpenalty }
     *     
     */
    public Armorcheckpenalty getArmorcheckpenalty() {
        return armorcheckpenalty;
    }

    /**
     * Sets the value of the armorcheckpenalty property.
     * 
     * @param value
     *     allowed object is
     *     {@link Armorcheckpenalty }
     *     
     */
    public void setArmorcheckpenalty(Armorcheckpenalty value) {
        this.armorcheckpenalty = value;
    }

    /**
     * Gets the value of the dragload property.
     * 
     * @return
     *     possible object is
     *     {@link Dragload }
     *     
     */
    public Dragload getDragload() {
        return dragload;
    }

    /**
     * Sets the value of the dragload property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dragload }
     *     
     */
    public void setDragload(Dragload value) {
        this.dragload = value;
    }

    /**
     * Gets the value of the heavyarmor property.
     * 
     * @return
     *     possible object is
     *     {@link Heavyarmor }
     *     
     */
    public Heavyarmor getHeavyarmor() {
        return heavyarmor;
    }

    /**
     * Sets the value of the heavyarmor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Heavyarmor }
     *     
     */
    public void setHeavyarmor(Heavyarmor value) {
        this.heavyarmor = value;
    }

    /**
     * Gets the value of the heavyload property.
     * 
     * @return
     *     possible object is
     *     {@link Heavyload }
     *     
     */
    public Heavyload getHeavyload() {
        return heavyload;
    }

    /**
     * Sets the value of the heavyload property.
     * 
     * @param value
     *     allowed object is
     *     {@link Heavyload }
     *     
     */
    public void setHeavyload(Heavyload value) {
        this.heavyload = value;
    }

    /**
     * Gets the value of the load property.
     * 
     * @return
     *     possible object is
     *     {@link Load }
     *     
     */
    public Load getLoad() {
        return load;
    }

    /**
     * Sets the value of the load property.
     * 
     * @param value
     *     allowed object is
     *     {@link Load }
     *     
     */
    public void setLoad(Load value) {
        this.load = value;
    }

    /**
     * Gets the value of the normalload property.
     * 
     * @return
     *     possible object is
     *     {@link Normalload }
     *     
     */
    public Normalload getNormalload() {
        return normalload;
    }

    /**
     * Sets the value of the normalload property.
     * 
     * @param value
     *     allowed object is
     *     {@link Normalload }
     *     
     */
    public void setNormalload(Normalload value) {
        this.normalload = value;
    }

}
