//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.10 at 10:15:41 PM EDT 
//


package net.edmacdonald.fantasyGrounds;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}bloodied"/>
 *         &lt;element ref="{}faileddeathsaves"/>
 *         &lt;element ref="{}maxdeathsaves"/>
 *         &lt;element ref="{}surge"/>
 *         &lt;element ref="{}surgemodifier"/>
 *         &lt;element ref="{}surgesmax"/>
 *         &lt;element ref="{}surgesused"/>
 *         &lt;element ref="{}temporary"/>
 *         &lt;element ref="{}total"/>
 *         &lt;element ref="{}wounds"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bloodied",
    "faileddeathsaves",
    "maxdeathsaves",
    "surge",
    "surgemodifier",
    "surgesmax",
    "surgesused",
    "temporary",
    "total",
    "wounds"
})
@XmlRootElement(name = "hp")
public class Hp {

    @XmlElement(required = true)
    protected Bloodied bloodied;
    @XmlElement(required = true)
    protected Faileddeathsaves faileddeathsaves;
    @XmlElement(required = true)
    protected Maxdeathsaves maxdeathsaves;
    @XmlElement(required = true)
    protected Surge surge;
    @XmlElement(required = true)
    protected Surgemodifier surgemodifier;
    @XmlElement(required = true)
    protected Surgesmax surgesmax;
    @XmlElement(required = true)
    protected Surgesused surgesused;
    @XmlElement(required = true)
    protected Temporary temporary;
    @XmlElement(required = true)
    protected Total total;
    @XmlElement(required = true)
    protected Wounds wounds;

    /**
     * Gets the value of the bloodied property.
     * 
     * @return
     *     possible object is
     *     {@link Bloodied }
     *     
     */
    public Bloodied getBloodied() {
        return bloodied;
    }

    /**
     * Sets the value of the bloodied property.
     * 
     * @param value
     *     allowed object is
     *     {@link Bloodied }
     *     
     */
    public void setBloodied(Bloodied value) {
        this.bloodied = value;
    }

    /**
     * Gets the value of the faileddeathsaves property.
     * 
     * @return
     *     possible object is
     *     {@link Faileddeathsaves }
     *     
     */
    public Faileddeathsaves getFaileddeathsaves() {
        return faileddeathsaves;
    }

    /**
     * Sets the value of the faileddeathsaves property.
     * 
     * @param value
     *     allowed object is
     *     {@link Faileddeathsaves }
     *     
     */
    public void setFaileddeathsaves(Faileddeathsaves value) {
        this.faileddeathsaves = value;
    }

    /**
     * Gets the value of the maxdeathsaves property.
     * 
     * @return
     *     possible object is
     *     {@link Maxdeathsaves }
     *     
     */
    public Maxdeathsaves getMaxdeathsaves() {
        return maxdeathsaves;
    }

    /**
     * Sets the value of the maxdeathsaves property.
     * 
     * @param value
     *     allowed object is
     *     {@link Maxdeathsaves }
     *     
     */
    public void setMaxdeathsaves(Maxdeathsaves value) {
        this.maxdeathsaves = value;
    }

    /**
     * Gets the value of the surge property.
     * 
     * @return
     *     possible object is
     *     {@link Surge }
     *     
     */
    public Surge getSurge() {
        return surge;
    }

    /**
     * Sets the value of the surge property.
     * 
     * @param value
     *     allowed object is
     *     {@link Surge }
     *     
     */
    public void setSurge(Surge value) {
        this.surge = value;
    }

    /**
     * Gets the value of the surgemodifier property.
     * 
     * @return
     *     possible object is
     *     {@link Surgemodifier }
     *     
     */
    public Surgemodifier getSurgemodifier() {
        return surgemodifier;
    }

    /**
     * Sets the value of the surgemodifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link Surgemodifier }
     *     
     */
    public void setSurgemodifier(Surgemodifier value) {
        this.surgemodifier = value;
    }

    /**
     * Gets the value of the surgesmax property.
     * 
     * @return
     *     possible object is
     *     {@link Surgesmax }
     *     
     */
    public Surgesmax getSurgesmax() {
        return surgesmax;
    }

    /**
     * Sets the value of the surgesmax property.
     * 
     * @param value
     *     allowed object is
     *     {@link Surgesmax }
     *     
     */
    public void setSurgesmax(Surgesmax value) {
        this.surgesmax = value;
    }

    /**
     * Gets the value of the surgesused property.
     * 
     * @return
     *     possible object is
     *     {@link Surgesused }
     *     
     */
    public Surgesused getSurgesused() {
        return surgesused;
    }

    /**
     * Sets the value of the surgesused property.
     * 
     * @param value
     *     allowed object is
     *     {@link Surgesused }
     *     
     */
    public void setSurgesused(Surgesused value) {
        this.surgesused = value;
    }

    /**
     * Gets the value of the temporary property.
     * 
     * @return
     *     possible object is
     *     {@link Temporary }
     *     
     */
    public Temporary getTemporary() {
        return temporary;
    }

    /**
     * Sets the value of the temporary property.
     * 
     * @param value
     *     allowed object is
     *     {@link Temporary }
     *     
     */
    public void setTemporary(Temporary value) {
        this.temporary = value;
    }

    /**
     * Gets the value of the total property.
     * 
     * @return
     *     possible object is
     *     {@link Total }
     *     
     */
    public Total getTotal() {
        return total;
    }

    /**
     * Sets the value of the total property.
     * 
     * @param value
     *     allowed object is
     *     {@link Total }
     *     
     */
    public void setTotal(Total value) {
        this.total = value;
    }

    /**
     * Gets the value of the wounds property.
     * 
     * @return
     *     possible object is
     *     {@link Wounds }
     *     
     */
    public Wounds getWounds() {
        return wounds;
    }

    /**
     * Sets the value of the wounds property.
     * 
     * @param value
     *     allowed object is
     *     {@link Wounds }
     *     
     */
    public void setWounds(Wounds value) {
        this.wounds = value;
    }

}
