//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.10 at 10:15:41 PM EDT 
//


package net.edmacdonald.fantasyGrounds;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element ref="{}bonus"/>
 *             &lt;element ref="{}carried"/>
 *             &lt;element ref="{}class"/>
 *             &lt;element ref="{}cost"/>
 *             &lt;element ref="{}count"/>
 *             &lt;element ref="{}critical"/>
 *             &lt;element ref="{}enhancement"/>
 *             &lt;element ref="{}flavor"/>
 *             &lt;element ref="{}level"/>
 *             &lt;element ref="{}mitype"/>
 *             &lt;element ref="{}name"/>
 *             &lt;element ref="{}powers"/>
 *             &lt;element ref="{}shortcut"/>
 *           &lt;/sequence>
 *           &lt;sequence>
 *             &lt;element ref="{}classskill"/>
 *             &lt;element ref="{}label"/>
 *             &lt;element ref="{}misc"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *         &lt;element ref="{}showonminisheet"/>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element ref="{}statname"/>
 *             &lt;element ref="{}total"/>
 *             &lt;element ref="{}trained"/>
 *           &lt;/sequence>
 *           &lt;sequence>
 *             &lt;element ref="{}subclass"/>
 *             &lt;element ref="{}weight"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bonus",
    "carried",
    "clazz",
    "cost",
    "count",
    "critical",
    "enhancement",
    "flavor",
    "level",
    "mitype",
    "name",
    "powers",
    "shortcut",
    "classskill",
    "label",
    "misc",
    "showonminisheet",
    "statname",
    "total",
    "trained",
    "subclass",
    "weight"
})
@XmlRootElement(name = "id-00014")
public class Id00014 {

    protected Bonus bonus;
    protected Carried carried;
    @XmlElement(name = "class")
    protected Class clazz;
    protected Cost cost;
    protected Count count;
    protected Critical critical;
    protected Enhancement enhancement;
    protected Flavor flavor;
    protected Level level;
    protected Mitype mitype;
    protected Name name;
    protected Powers powers;
    protected Shortcut shortcut;
    protected Classskill classskill;
    protected Label label;
    protected Misc misc;
    @XmlElement(required = true)
    protected Showonminisheet showonminisheet;
    protected Statname statname;
    protected Total total;
    protected Trained trained;
    protected Subclass subclass;
    protected Weight weight;

    /**
     * Gets the value of the bonus property.
     * 
     * @return
     *     possible object is
     *     {@link Bonus }
     *     
     */
    public Bonus getBonus() {
        return bonus;
    }

    /**
     * Sets the value of the bonus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Bonus }
     *     
     */
    public void setBonus(Bonus value) {
        this.bonus = value;
    }

    /**
     * Gets the value of the carried property.
     * 
     * @return
     *     possible object is
     *     {@link Carried }
     *     
     */
    public Carried getCarried() {
        return carried;
    }

    /**
     * Sets the value of the carried property.
     * 
     * @param value
     *     allowed object is
     *     {@link Carried }
     *     
     */
    public void setCarried(Carried value) {
        this.carried = value;
    }

    /**
     * Gets the value of the clazz property.
     * 
     * @return
     *     possible object is
     *     {@link Class }
     *     
     */
    public Class getClazz() {
        return clazz;
    }

    /**
     * Sets the value of the clazz property.
     * 
     * @param value
     *     allowed object is
     *     {@link Class }
     *     
     */
    public void setClazz(Class value) {
        this.clazz = value;
    }

    /**
     * Gets the value of the cost property.
     * 
     * @return
     *     possible object is
     *     {@link Cost }
     *     
     */
    public Cost getCost() {
        return cost;
    }

    /**
     * Sets the value of the cost property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cost }
     *     
     */
    public void setCost(Cost value) {
        this.cost = value;
    }

    /**
     * Gets the value of the count property.
     * 
     * @return
     *     possible object is
     *     {@link Count }
     *     
     */
    public Count getCount() {
        return count;
    }

    /**
     * Sets the value of the count property.
     * 
     * @param value
     *     allowed object is
     *     {@link Count }
     *     
     */
    public void setCount(Count value) {
        this.count = value;
    }

    /**
     * Gets the value of the critical property.
     * 
     * @return
     *     possible object is
     *     {@link Critical }
     *     
     */
    public Critical getCritical() {
        return critical;
    }

    /**
     * Sets the value of the critical property.
     * 
     * @param value
     *     allowed object is
     *     {@link Critical }
     *     
     */
    public void setCritical(Critical value) {
        this.critical = value;
    }

    /**
     * Gets the value of the enhancement property.
     * 
     * @return
     *     possible object is
     *     {@link Enhancement }
     *     
     */
    public Enhancement getEnhancement() {
        return enhancement;
    }

    /**
     * Sets the value of the enhancement property.
     * 
     * @param value
     *     allowed object is
     *     {@link Enhancement }
     *     
     */
    public void setEnhancement(Enhancement value) {
        this.enhancement = value;
    }

    /**
     * Gets the value of the flavor property.
     * 
     * @return
     *     possible object is
     *     {@link Flavor }
     *     
     */
    public Flavor getFlavor() {
        return flavor;
    }

    /**
     * Sets the value of the flavor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Flavor }
     *     
     */
    public void setFlavor(Flavor value) {
        this.flavor = value;
    }

    /**
     * Gets the value of the level property.
     * 
     * @return
     *     possible object is
     *     {@link Level }
     *     
     */
    public Level getLevel() {
        return level;
    }

    /**
     * Sets the value of the level property.
     * 
     * @param value
     *     allowed object is
     *     {@link Level }
     *     
     */
    public void setLevel(Level value) {
        this.level = value;
    }

    /**
     * Gets the value of the mitype property.
     * 
     * @return
     *     possible object is
     *     {@link Mitype }
     *     
     */
    public Mitype getMitype() {
        return mitype;
    }

    /**
     * Sets the value of the mitype property.
     * 
     * @param value
     *     allowed object is
     *     {@link Mitype }
     *     
     */
    public void setMitype(Mitype value) {
        this.mitype = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link Name }
     *     
     */
    public Name getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link Name }
     *     
     */
    public void setName(Name value) {
        this.name = value;
    }

    /**
     * Gets the value of the powers property.
     * 
     * @return
     *     possible object is
     *     {@link Powers }
     *     
     */
    public Powers getPowers() {
        return powers;
    }

    /**
     * Sets the value of the powers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Powers }
     *     
     */
    public void setPowers(Powers value) {
        this.powers = value;
    }

    /**
     * Gets the value of the shortcut property.
     * 
     * @return
     *     possible object is
     *     {@link Shortcut }
     *     
     */
    public Shortcut getShortcut() {
        return shortcut;
    }

    /**
     * Sets the value of the shortcut property.
     * 
     * @param value
     *     allowed object is
     *     {@link Shortcut }
     *     
     */
    public void setShortcut(Shortcut value) {
        this.shortcut = value;
    }

    /**
     * Gets the value of the classskill property.
     * 
     * @return
     *     possible object is
     *     {@link Classskill }
     *     
     */
    public Classskill getClassskill() {
        return classskill;
    }

    /**
     * Sets the value of the classskill property.
     * 
     * @param value
     *     allowed object is
     *     {@link Classskill }
     *     
     */
    public void setClassskill(Classskill value) {
        this.classskill = value;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link Label }
     *     
     */
    public Label getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link Label }
     *     
     */
    public void setLabel(Label value) {
        this.label = value;
    }

    /**
     * Gets the value of the misc property.
     * 
     * @return
     *     possible object is
     *     {@link Misc }
     *     
     */
    public Misc getMisc() {
        return misc;
    }

    /**
     * Sets the value of the misc property.
     * 
     * @param value
     *     allowed object is
     *     {@link Misc }
     *     
     */
    public void setMisc(Misc value) {
        this.misc = value;
    }

    /**
     * Gets the value of the showonminisheet property.
     * 
     * @return
     *     possible object is
     *     {@link Showonminisheet }
     *     
     */
    public Showonminisheet getShowonminisheet() {
        return showonminisheet;
    }

    /**
     * Sets the value of the showonminisheet property.
     * 
     * @param value
     *     allowed object is
     *     {@link Showonminisheet }
     *     
     */
    public void setShowonminisheet(Showonminisheet value) {
        this.showonminisheet = value;
    }

    /**
     * Gets the value of the statname property.
     * 
     * @return
     *     possible object is
     *     {@link Statname }
     *     
     */
    public Statname getStatname() {
        return statname;
    }

    /**
     * Sets the value of the statname property.
     * 
     * @param value
     *     allowed object is
     *     {@link Statname }
     *     
     */
    public void setStatname(Statname value) {
        this.statname = value;
    }

    /**
     * Gets the value of the total property.
     * 
     * @return
     *     possible object is
     *     {@link Total }
     *     
     */
    public Total getTotal() {
        return total;
    }

    /**
     * Sets the value of the total property.
     * 
     * @param value
     *     allowed object is
     *     {@link Total }
     *     
     */
    public void setTotal(Total value) {
        this.total = value;
    }

    /**
     * Gets the value of the trained property.
     * 
     * @return
     *     possible object is
     *     {@link Trained }
     *     
     */
    public Trained getTrained() {
        return trained;
    }

    /**
     * Sets the value of the trained property.
     * 
     * @param value
     *     allowed object is
     *     {@link Trained }
     *     
     */
    public void setTrained(Trained value) {
        this.trained = value;
    }

    /**
     * Gets the value of the subclass property.
     * 
     * @return
     *     possible object is
     *     {@link Subclass }
     *     
     */
    public Subclass getSubclass() {
        return subclass;
    }

    /**
     * Sets the value of the subclass property.
     * 
     * @param value
     *     allowed object is
     *     {@link Subclass }
     *     
     */
    public void setSubclass(Subclass value) {
        this.subclass = value;
    }

    /**
     * Gets the value of the weight property.
     * 
     * @return
     *     possible object is
     *     {@link Weight }
     *     
     */
    public Weight getWeight() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Weight }
     *     
     */
    public void setWeight(Weight value) {
        this.weight = value;
    }

}
