//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.10 at 10:15:41 PM EDT 
//


package net.edmacdonald.fantasyGrounds;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}carried"/>
 *         &lt;element ref="{}class"/>
 *         &lt;element ref="{}cost"/>
 *         &lt;element ref="{}count"/>
 *         &lt;element ref="{}flavor"/>
 *         &lt;element ref="{}level"/>
 *         &lt;element ref="{}mitype"/>
 *         &lt;element ref="{}name"/>
 *         &lt;element ref="{}powers"/>
 *         &lt;element ref="{}shortcut"/>
 *         &lt;element ref="{}showonminisheet"/>
 *         &lt;element ref="{}subclass"/>
 *         &lt;element ref="{}weight"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "carried",
    "clazz",
    "cost",
    "count",
    "flavor",
    "level",
    "mitype",
    "name",
    "powers",
    "shortcut",
    "showonminisheet",
    "subclass",
    "weight"
})
@XmlRootElement(name = "id-00019")
public class Id00019 {

    @XmlElement(required = true)
    protected Carried carried;
    @XmlElement(name = "class", required = true)
    protected Class clazz;
    @XmlElement(required = true)
    protected Cost cost;
    @XmlElement(required = true)
    protected Count count;
    @XmlElement(required = true)
    protected Flavor flavor;
    @XmlElement(required = true)
    protected Level level;
    @XmlElement(required = true)
    protected Mitype mitype;
    @XmlElement(required = true)
    protected Name name;
    @XmlElement(required = true)
    protected Powers powers;
    @XmlElement(required = true)
    protected Shortcut shortcut;
    @XmlElement(required = true)
    protected Showonminisheet showonminisheet;
    @XmlElement(required = true)
    protected Subclass subclass;
    @XmlElement(required = true)
    protected Weight weight;

    /**
     * Gets the value of the carried property.
     * 
     * @return
     *     possible object is
     *     {@link Carried }
     *     
     */
    public Carried getCarried() {
        return carried;
    }

    /**
     * Sets the value of the carried property.
     * 
     * @param value
     *     allowed object is
     *     {@link Carried }
     *     
     */
    public void setCarried(Carried value) {
        this.carried = value;
    }

    /**
     * Gets the value of the clazz property.
     * 
     * @return
     *     possible object is
     *     {@link Class }
     *     
     */
    public Class getClazz() {
        return clazz;
    }

    /**
     * Sets the value of the clazz property.
     * 
     * @param value
     *     allowed object is
     *     {@link Class }
     *     
     */
    public void setClazz(Class value) {
        this.clazz = value;
    }

    /**
     * Gets the value of the cost property.
     * 
     * @return
     *     possible object is
     *     {@link Cost }
     *     
     */
    public Cost getCost() {
        return cost;
    }

    /**
     * Sets the value of the cost property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cost }
     *     
     */
    public void setCost(Cost value) {
        this.cost = value;
    }

    /**
     * Gets the value of the count property.
     * 
     * @return
     *     possible object is
     *     {@link Count }
     *     
     */
    public Count getCount() {
        return count;
    }

    /**
     * Sets the value of the count property.
     * 
     * @param value
     *     allowed object is
     *     {@link Count }
     *     
     */
    public void setCount(Count value) {
        this.count = value;
    }

    /**
     * Gets the value of the flavor property.
     * 
     * @return
     *     possible object is
     *     {@link Flavor }
     *     
     */
    public Flavor getFlavor() {
        return flavor;
    }

    /**
     * Sets the value of the flavor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Flavor }
     *     
     */
    public void setFlavor(Flavor value) {
        this.flavor = value;
    }

    /**
     * Gets the value of the level property.
     * 
     * @return
     *     possible object is
     *     {@link Level }
     *     
     */
    public Level getLevel() {
        return level;
    }

    /**
     * Sets the value of the level property.
     * 
     * @param value
     *     allowed object is
     *     {@link Level }
     *     
     */
    public void setLevel(Level value) {
        this.level = value;
    }

    /**
     * Gets the value of the mitype property.
     * 
     * @return
     *     possible object is
     *     {@link Mitype }
     *     
     */
    public Mitype getMitype() {
        return mitype;
    }

    /**
     * Sets the value of the mitype property.
     * 
     * @param value
     *     allowed object is
     *     {@link Mitype }
     *     
     */
    public void setMitype(Mitype value) {
        this.mitype = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link Name }
     *     
     */
    public Name getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link Name }
     *     
     */
    public void setName(Name value) {
        this.name = value;
    }

    /**
     * Gets the value of the powers property.
     * 
     * @return
     *     possible object is
     *     {@link Powers }
     *     
     */
    public Powers getPowers() {
        return powers;
    }

    /**
     * Sets the value of the powers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Powers }
     *     
     */
    public void setPowers(Powers value) {
        this.powers = value;
    }

    /**
     * Gets the value of the shortcut property.
     * 
     * @return
     *     possible object is
     *     {@link Shortcut }
     *     
     */
    public Shortcut getShortcut() {
        return shortcut;
    }

    /**
     * Sets the value of the shortcut property.
     * 
     * @param value
     *     allowed object is
     *     {@link Shortcut }
     *     
     */
    public void setShortcut(Shortcut value) {
        this.shortcut = value;
    }

    /**
     * Gets the value of the showonminisheet property.
     * 
     * @return
     *     possible object is
     *     {@link Showonminisheet }
     *     
     */
    public Showonminisheet getShowonminisheet() {
        return showonminisheet;
    }

    /**
     * Sets the value of the showonminisheet property.
     * 
     * @param value
     *     allowed object is
     *     {@link Showonminisheet }
     *     
     */
    public void setShowonminisheet(Showonminisheet value) {
        this.showonminisheet = value;
    }

    /**
     * Gets the value of the subclass property.
     * 
     * @return
     *     possible object is
     *     {@link Subclass }
     *     
     */
    public Subclass getSubclass() {
        return subclass;
    }

    /**
     * Sets the value of the subclass property.
     * 
     * @param value
     *     allowed object is
     *     {@link Subclass }
     *     
     */
    public void setSubclass(Subclass value) {
        this.subclass = value;
    }

    /**
     * Gets the value of the weight property.
     * 
     * @return
     *     possible object is
     *     {@link Weight }
     *     
     */
    public Weight getWeight() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Weight }
     *     
     */
    public void setWeight(Weight value) {
        this.weight = value;
    }

}
