//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.10 at 10:15:41 PM EDT 
//


package net.edmacdonald.fantasyGrounds;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.edmacdonald.fantasyGrounds package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Slot6_QNAME = new QName("", "slot6");
    private final static QName _Recordname_QNAME = new QName("", "recordname");
    private final static QName _Slot1_QNAME = new QName("", "slot1");
    private final static QName _Slot2_QNAME = new QName("", "slot2");
    private final static QName _Slot3_QNAME = new QName("", "slot3");
    private final static QName _Slot4_QNAME = new QName("", "slot4");
    private final static QName _Slot5_QNAME = new QName("", "slot5");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.edmacdonald.fantasyGrounds
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Maxdeathsaves }
     * 
     */
    public Maxdeathsaves createMaxdeathsaves() {
        return new Maxdeathsaves();
    }

    /**
     * Create an instance of {@link Bonus }
     * 
     */
    public Bonus createBonus() {
        return new Bonus();
    }

    /**
     * Create an instance of {@link Level }
     * 
     */
    public Level createLevel() {
        return new Level();
    }

    /**
     * Create an instance of {@link Focus }
     * 
     */
    public Focus createFocus() {
        return new Focus();
    }

    /**
     * Create an instance of {@link Encounterspecial }
     * 
     */
    public Encounterspecial createEncounterspecial() {
        return new Encounterspecial();
    }

    /**
     * Create an instance of {@link Id00016 }
     * 
     */
    public Id00016 createId00016() {
        return new Id00016();
    }

    /**
     * Create an instance of {@link Id00001 }
     * 
     */
    public Id00001 createId00001() {
        return new Id00001();
    }

    /**
     * Create an instance of {@link Id00011 }
     * 
     */
    public Id00011 createId00011() {
        return new Id00011();
    }

    /**
     * Create an instance of {@link Total }
     * 
     */
    public Total createTotal() {
        return new Total();
    }

    /**
     * Create an instance of {@link Damagebonus }
     * 
     */
    public Damagebonus createDamagebonus() {
        return new Damagebonus();
    }

    /**
     * Create an instance of {@link Range }
     * 
     */
    public Range createRange() {
        return new Range();
    }

    /**
     * Create an instance of {@link Melee }
     * 
     */
    public Melee createMelee() {
        return new Melee();
    }

    /**
     * Create an instance of {@link Surge }
     * 
     */
    public Surge createSurge() {
        return new Surge();
    }

    /**
     * Create an instance of {@link Attackstatmodifier }
     * 
     */
    public Attackstatmodifier createAttackstatmodifier() {
        return new Attackstatmodifier();
    }

    /**
     * Create an instance of {@link Id00013 }
     * 
     */
    public Id00013 createId00013() {
        return new Id00013();
    }

    /**
     * Create an instance of {@link Id00010 }
     * 
     */
    public Id00010 createId00010() {
        return new Id00010();
    }

    /**
     * Create an instance of {@link Armor }
     * 
     */
    public Armor createArmor() {
        return new Armor();
    }

    /**
     * Create an instance of {@link Heavyload }
     * 
     */
    public Heavyload createHeavyload() {
        return new Heavyload();
    }

    /**
     * Create an instance of {@link Id00014 }
     * 
     */
    public Id00014 createId00014() {
        return new Id00014();
    }

    /**
     * Create an instance of {@link Bloodied }
     * 
     */
    public Bloodied createBloodied() {
        return new Bloodied();
    }

    /**
     * Create an instance of {@link Damageweaponmult }
     * 
     */
    public Damageweaponmult createDamageweaponmult() {
        return new Damageweaponmult();
    }

    /**
     * Create an instance of {@link Statname }
     * 
     */
    public Statname createStatname() {
        return new Statname();
    }

    /**
     * Create an instance of {@link Link }
     * 
     */
    public Link createLink() {
        return new Link();
    }

    /**
     * Create an instance of {@link Exp }
     * 
     */
    public Exp createExp() {
        return new Exp();
    }

    /**
     * Create an instance of {@link Passiveperception }
     * 
     */
    public Passiveperception createPassiveperception() {
        return new Passiveperception();
    }

    /**
     * Create an instance of {@link Intelligence }
     * 
     */
    public Intelligence createIntelligence() {
        return new Intelligence();
    }

    /**
     * Create an instance of {@link A2Cantrip }
     * 
     */
    public A2Cantrip createA2Cantrip() {
        return new A2Cantrip();
    }

    /**
     * Create an instance of {@link Effectsavemod }
     * 
     */
    public Effectsavemod createEffectsavemod() {
        return new Effectsavemod();
    }

    /**
     * Create an instance of {@link Id00018 }
     * 
     */
    public Id00018 createId00018() {
        return new Id00018();
    }

    /**
     * Create an instance of {@link Defenses }
     * 
     */
    public Defenses createDefenses() {
        return new Defenses();
    }

    /**
     * Create an instance of {@link Class }
     * 
     */
    public Class createClass() {
        return new Class();
    }

    /**
     * Create an instance of {@link Surgesused }
     * 
     */
    public Surgesused createSurgesused() {
        return new Surgesused();
    }

    /**
     * Create an instance of {@link Prepared }
     * 
     */
    public Prepared createPrepared() {
        return new Prepared();
    }

    /**
     * Create an instance of {@link Fortitude }
     * 
     */
    public Fortitude createFortitude() {
        return new Fortitude();
    }

    /**
     * Create an instance of {@link Criticaldice }
     * 
     */
    public Criticaldice createCriticaldice() {
        return new Criticaldice();
    }

    /**
     * Create an instance of {@link Check }
     * 
     */
    public Check createCheck() {
        return new Check();
    }

    /**
     * Create an instance of {@link Powershow }
     * 
     */
    public Powershow createPowershow() {
        return new Powershow();
    }

    /**
     * Create an instance of {@link Id00017 }
     * 
     */
    public Id00017 createId00017() {
        return new Id00017();
    }

    /**
     * Create an instance of {@link Speed }
     * 
     */
    public Speed createSpeed() {
        return new Speed();
    }

    /**
     * Create an instance of {@link Damagetype }
     * 
     */
    public Damagetype createDamagetype() {
        return new Damagetype();
    }

    /**
     * Create an instance of {@link B1Encounter }
     * 
     */
    public B1Encounter createB1Encounter() {
        return new B1Encounter();
    }

    /**
     * Create an instance of {@link Paragon }
     * 
     */
    public Paragon createParagon() {
        return new Paragon();
    }

    /**
     * Create an instance of {@link Coins }
     * 
     */
    public Coins createCoins() {
        return new Coins();
    }

    /**
     * Create an instance of {@link Wisdom }
     * 
     */
    public Wisdom createWisdom() {
        return new Wisdom();
    }

    /**
     * Create an instance of {@link Name }
     * 
     */
    public Name createName() {
        return new Name();
    }

    /**
     * Create an instance of {@link B2Channeldivinity }
     * 
     */
    public B2Channeldivinity createB2Channeldivinity() {
        return new B2Channeldivinity();
    }

    /**
     * Create an instance of {@link Weight }
     * 
     */
    public Weight createWeight() {
        return new Weight();
    }

    /**
     * Create an instance of {@link Weaponlist }
     * 
     */
    public Weaponlist createWeaponlist() {
        return new Weaponlist();
    }

    /**
     * Create an instance of {@link Channeldivinity }
     * 
     */
    public Channeldivinity createChanneldivinity() {
        return new Channeldivinity();
    }

    /**
     * Create an instance of {@link Heavyarmor }
     * 
     */
    public Heavyarmor createHeavyarmor() {
        return new Heavyarmor();
    }

    /**
     * Create an instance of {@link Faileddeathsaves }
     * 
     */
    public Faileddeathsaves createFaileddeathsaves() {
        return new Faileddeathsaves();
    }

    /**
     * Create an instance of {@link Source }
     * 
     */
    public Source createSource() {
        return new Source();
    }

    /**
     * Create an instance of {@link Final }
     * 
     */
    public Final createFinal() {
        return new Final();
    }

    /**
     * Create an instance of {@link Expiration }
     * 
     */
    public Expiration createExpiration() {
        return new Expiration();
    }

    /**
     * Create an instance of {@link Armorcheckmultiplier }
     * 
     */
    public Armorcheckmultiplier createArmorcheckmultiplier() {
        return new Armorcheckmultiplier();
    }

    /**
     * Create an instance of {@link CDaily }
     * 
     */
    public CDaily createCDaily() {
        return new CDaily();
    }

    /**
     * Create an instance of {@link Race }
     * 
     */
    public Race createRace() {
        return new Race();
    }

    /**
     * Create an instance of {@link Actionpoints }
     * 
     */
    public Actionpoints createActionpoints() {
        return new Actionpoints();
    }

    /**
     * Create an instance of {@link Surgemodifier }
     * 
     */
    public Surgemodifier createSurgemodifier() {
        return new Surgemodifier();
    }

    /**
     * Create an instance of {@link Maxammo }
     * 
     */
    public Maxammo createMaxammo() {
        return new Maxammo();
    }

    /**
     * Create an instance of {@link Id00005 }
     * 
     */
    public Id00005 createId00005() {
        return new Id00005();
    }

    /**
     * Create an instance of {@link Initiative }
     * 
     */
    public Initiative createInitiative() {
        return new Initiative();
    }

    /**
     * Create an instance of {@link Prop002 }
     * 
     */
    public Prop002 createProp002() {
        return new Prop002();
    }

    /**
     * Create an instance of {@link Dragload }
     * 
     */
    public Dragload createDragload() {
        return new Dragload();
    }

    /**
     * Create an instance of {@link Id00012 }
     * 
     */
    public Id00012 createId00012() {
        return new Id00012();
    }

    /**
     * Create an instance of {@link Recharge }
     * 
     */
    public Recharge createRecharge() {
        return new Recharge();
    }

    /**
     * Create an instance of {@link Damagestat }
     * 
     */
    public Damagestat createDamagestat() {
        return new Damagestat();
    }

    /**
     * Create an instance of {@link Count }
     * 
     */
    public Count createCount() {
        return new Count();
    }

    /**
     * Create an instance of {@link Id00015 }
     * 
     */
    public Id00015 createId00015() {
        return new Id00015();
    }

    /**
     * Create an instance of {@link Reflex }
     * 
     */
    public Reflex createReflex() {
        return new Reflex();
    }

    /**
     * Create an instance of {@link Attackstat }
     * 
     */
    public Attackstat createAttackstat() {
        return new Attackstat();
    }

    /**
     * Create an instance of {@link Cost }
     * 
     */
    public Cost createCost() {
        return new Cost();
    }

    /**
     * Create an instance of {@link Shortcut }
     * 
     */
    public Shortcut createShortcut() {
        return new Shortcut();
    }

    /**
     * Create an instance of {@link Trained }
     * 
     */
    public Trained createTrained() {
        return new Trained();
    }

    /**
     * Create an instance of {@link Effects }
     * 
     */
    public Effects createEffects() {
        return new Effects();
    }

    /**
     * Create an instance of {@link A11Atwillspecial }
     * 
     */
    public A11Atwillspecial createA11Atwillspecial() {
        return new A11Atwillspecial();
    }

    /**
     * Create an instance of {@link Amt }
     * 
     */
    public Amt createAmt() {
        return new Amt();
    }

    /**
     * Create an instance of {@link A0Situational }
     * 
     */
    public A0Situational createA0Situational() {
        return new A0Situational();
    }

    /**
     * Create an instance of {@link Id00004 }
     * 
     */
    public Id00004 createId00004() {
        return new Id00004();
    }

    /**
     * Create an instance of {@link Id00019 }
     * 
     */
    public Id00019 createId00019() {
        return new Id00019();
    }

    /**
     * Create an instance of {@link Label }
     * 
     */
    public Label createLabel() {
        return new Label();
    }

    /**
     * Create an instance of {@link Wounds }
     * 
     */
    public Wounds createWounds() {
        return new Wounds();
    }

    /**
     * Create an instance of {@link Flavor }
     * 
     */
    public Flavor createFlavor() {
        return new Flavor();
    }

    /**
     * Create an instance of {@link Atwillspecial }
     * 
     */
    public Atwillspecial createAtwillspecial() {
        return new Atwillspecial();
    }

    /**
     * Create an instance of {@link Combattoken }
     * 
     */
    public Combattoken createCombattoken() {
        return new Combattoken();
    }

    /**
     * Create an instance of {@link Featlist }
     * 
     */
    public Featlist createFeatlist() {
        return new Featlist();
    }

    /**
     * Create an instance of {@link Subclass }
     * 
     */
    public Subclass createSubclass() {
        return new Subclass();
    }

    /**
     * Create an instance of {@link Attacks }
     * 
     */
    public Attacks createAttacks() {
        return new Attacks();
    }

    /**
     * Create an instance of {@link Id001 }
     * 
     */
    public Id001 createId001() {
        return new Id001();
    }

    /**
     * Create an instance of {@link Will }
     * 
     */
    public Will createWill() {
        return new Will();
    }

    /**
     * Create an instance of {@link Enhancement }
     * 
     */
    public Enhancement createEnhancement() {
        return new Enhancement();
    }

    /**
     * Create an instance of {@link Save }
     * 
     */
    public Save createSave() {
        return new Save();
    }

    /**
     * Create an instance of {@link Ranged }
     * 
     */
    public Ranged createRanged() {
        return new Ranged();
    }

    /**
     * Create an instance of {@link Id00007 }
     * 
     */
    public Id00007 createId00007() {
        return new Id00007();
    }

    /**
     * Create an instance of {@link EItemdaily }
     * 
     */
    public EItemdaily createEItemdaily() {
        return new EItemdaily();
    }

    /**
     * Create an instance of {@link Dexterity }
     * 
     */
    public Dexterity createDexterity() {
        return new Dexterity();
    }

    /**
     * Create an instance of {@link Shortdescription }
     * 
     */
    public Shortdescription createShortdescription() {
        return new Shortdescription();
    }

    /**
     * Create an instance of {@link DUtility }
     * 
     */
    public DUtility createDUtility() {
        return new DUtility();
    }

    /**
     * Create an instance of {@link Powerfocus }
     * 
     */
    public Powerfocus createPowerfocus() {
        return new Powerfocus();
    }

    /**
     * Create an instance of {@link Abilities }
     * 
     */
    public Abilities createAbilities() {
        return new Abilities();
    }

    /**
     * Create an instance of {@link Classskill }
     * 
     */
    public Classskill createClassskill() {
        return new Classskill();
    }

    /**
     * Create an instance of {@link Criticalbonus }
     * 
     */
    public Criticalbonus createCriticalbonus() {
        return new Criticalbonus();
    }

    /**
     * Create an instance of {@link Weapon }
     * 
     */
    public Weapon createWeapon() {
        return new Weapon();
    }

    /**
     * Create an instance of {@link Carried }
     * 
     */
    public Carried createCarried() {
        return new Carried();
    }

    /**
     * Create an instance of {@link Misc }
     * 
     */
    public Misc createMisc() {
        return new Misc();
    }

    /**
     * Create an instance of {@link Hp }
     * 
     */
    public Hp createHp() {
        return new Hp();
    }

    /**
     * Create an instance of {@link Id00002 }
     * 
     */
    public Id00002 createId00002() {
        return new Id00002();
    }

    /**
     * Create an instance of {@link A1Atwill }
     * 
     */
    public A1Atwill createA1Atwill() {
        return new A1Atwill();
    }

    /**
     * Create an instance of {@link Surgesmax }
     * 
     */
    public Surgesmax createSurgesmax() {
        return new Surgesmax();
    }

    /**
     * Create an instance of {@link Action }
     * 
     */
    public Action createAction() {
        return new Action();
    }

    /**
     * Create an instance of {@link Armorcheckpenalty }
     * 
     */
    public Armorcheckpenalty createArmorcheckpenalty() {
        return new Armorcheckpenalty();
    }

    /**
     * Create an instance of {@link Rangeincrement }
     * 
     */
    public Rangeincrement createRangeincrement() {
        return new Rangeincrement();
    }

    /**
     * Create an instance of {@link Powers }
     * 
     */
    public Powers createPowers() {
        return new Powers();
    }

    /**
     * Create an instance of {@link Charisma }
     * 
     */
    public Charisma createCharisma() {
        return new Charisma();
    }

    /**
     * Create an instance of {@link Keywords }
     * 
     */
    public Keywords createKeywords() {
        return new Keywords();
    }

    /**
     * Create an instance of {@link Expneeded }
     * 
     */
    public Expneeded createExpneeded() {
        return new Expneeded();
    }

    /**
     * Create an instance of {@link Mitype }
     * 
     */
    public Mitype createMitype() {
        return new Mitype();
    }

    /**
     * Create an instance of {@link Order }
     * 
     */
    public Order createOrder() {
        return new Order();
    }

    /**
     * Create an instance of {@link Damagedice }
     * 
     */
    public Damagedice createDamagedice() {
        return new Damagedice();
    }

    /**
     * Create an instance of {@link Damagestatmodifier }
     * 
     */
    public Damagestatmodifier createDamagestatmodifier() {
        return new Damagestatmodifier();
    }

    /**
     * Create an instance of {@link Powermode }
     * 
     */
    public Powermode createPowermode() {
        return new Powermode();
    }

    /**
     * Create an instance of {@link Proficiencyweapon }
     * 
     */
    public Proficiencyweapon createProficiencyweapon() {
        return new Proficiencyweapon();
    }

    /**
     * Create an instance of {@link Bonusmodifier }
     * 
     */
    public Bonusmodifier createBonusmodifier() {
        return new Bonusmodifier();
    }

    /**
     * Create an instance of {@link Strength }
     * 
     */
    public Strength createStrength() {
        return new Strength();
    }

    /**
     * Create an instance of {@link B11Encounterspecial }
     * 
     */
    public B11Encounterspecial createB11Encounterspecial() {
        return new B11Encounterspecial();
    }

    /**
     * Create an instance of {@link Levelbonus }
     * 
     */
    public Levelbonus createLevelbonus() {
        return new Levelbonus();
    }

    /**
     * Create an instance of {@link Used }
     * 
     */
    public Used createUsed() {
        return new Used();
    }

    /**
     * Create an instance of {@link Amount }
     * 
     */
    public Amount createAmount() {
        return new Amount();
    }

    /**
     * Create an instance of {@link Character }
     * 
     */
    public Character createCharacter() {
        return new Character();
    }

    /**
     * Create an instance of {@link Proficiencyarmor }
     * 
     */
    public Proficiencyarmor createProficiencyarmor() {
        return new Proficiencyarmor();
    }

    /**
     * Create an instance of {@link Passiveinsight }
     * 
     */
    public Passiveinsight createPassiveinsight() {
        return new Passiveinsight();
    }

    /**
     * Create an instance of {@link Ac }
     * 
     */
    public Ac createAc() {
        return new Ac();
    }

    /**
     * Create an instance of {@link Ability }
     * 
     */
    public Ability createAbility() {
        return new Ability();
    }

    /**
     * Create an instance of {@link Props }
     * 
     */
    public Props createProps() {
        return new Props();
    }

    /**
     * Create an instance of {@link Load }
     * 
     */
    public Load createLoad() {
        return new Load();
    }

    /**
     * Create an instance of {@link Encumbrance }
     * 
     */
    public Encumbrance createEncumbrance() {
        return new Encumbrance();
    }

    /**
     * Create an instance of {@link Id00003 }
     * 
     */
    public Id00003 createId00003() {
        return new Id00003();
    }

    /**
     * Create an instance of {@link Damage }
     * 
     */
    public Damage createDamage() {
        return new Damage();
    }

    /**
     * Create an instance of {@link Id00008 }
     * 
     */
    public Id00008 createId00008() {
        return new Id00008();
    }

    /**
     * Create an instance of {@link Specialabilitylist }
     * 
     */
    public Specialabilitylist createSpecialabilitylist() {
        return new Specialabilitylist();
    }

    /**
     * Create an instance of {@link Attackdef }
     * 
     */
    public Attackdef createAttackdef() {
        return new Attackdef();
    }

    /**
     * Create an instance of {@link Score }
     * 
     */
    public Score createScore() {
        return new Score();
    }

    /**
     * Create an instance of {@link Cantrip }
     * 
     */
    public Cantrip createCantrip() {
        return new Cantrip();
    }

    /**
     * Create an instance of {@link Showonminisheet }
     * 
     */
    public Showonminisheet createShowonminisheet() {
        return new Showonminisheet();
    }

    /**
     * Create an instance of {@link Usesavailable }
     * 
     */
    public Usesavailable createUsesavailable() {
        return new Usesavailable();
    }

    /**
     * Create an instance of {@link Constitution }
     * 
     */
    public Constitution createConstitution() {
        return new Constitution();
    }

    /**
     * Create an instance of {@link Power }
     * 
     */
    public Power createPower() {
        return new Power();
    }

    /**
     * Create an instance of {@link Prop001 }
     * 
     */
    public Prop001 createProp001() {
        return new Prop001();
    }

    /**
     * Create an instance of {@link Normalload }
     * 
     */
    public Normalload createNormalload() {
        return new Normalload();
    }

    /**
     * Create an instance of {@link Implement }
     * 
     */
    public Implement createImplement() {
        return new Implement();
    }

    /**
     * Create an instance of {@link Damagebasicdice }
     * 
     */
    public Damagebasicdice createDamagebasicdice() {
        return new Damagebasicdice();
    }

    /**
     * Create an instance of {@link Critical }
     * 
     */
    public Critical createCritical() {
        return new Critical();
    }

    /**
     * Create an instance of {@link Type }
     * 
     */
    public Type createType() {
        return new Type();
    }

    /**
     * Create an instance of {@link Skilllist }
     * 
     */
    public Skilllist createSkilllist() {
        return new Skilllist();
    }

    /**
     * Create an instance of {@link Base }
     * 
     */
    public Base createBase() {
        return new Base();
    }

    /**
     * Create an instance of {@link Inventorylist }
     * 
     */
    public Inventorylist createInventorylist() {
        return new Inventorylist();
    }

    /**
     * Create an instance of {@link Id00006 }
     * 
     */
    public Id00006 createId00006() {
        return new Id00006();
    }

    /**
     * Create an instance of {@link Id00009 }
     * 
     */
    public Id00009 createId00009() {
        return new Id00009();
    }

    /**
     * Create an instance of {@link Temporary }
     * 
     */
    public Temporary createTemporary() {
        return new Temporary();
    }

    /**
     * Create an instance of {@link Root }
     * 
     */
    public Root createRoot() {
        return new Root();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Amount }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "slot6")
    public JAXBElement<Amount> createSlot6(Amount value) {
        return new JAXBElement<Amount>(_Slot6_QNAME, Amount.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "recordname")
    public JAXBElement<String> createRecordname(String value) {
        return new JAXBElement<String>(_Recordname_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Amount }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "slot1")
    public JAXBElement<Amount> createSlot1(Amount value) {
        return new JAXBElement<Amount>(_Slot1_QNAME, Amount.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Amount }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "slot2")
    public JAXBElement<Amount> createSlot2(Amount value) {
        return new JAXBElement<Amount>(_Slot2_QNAME, Amount.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Amount }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "slot3")
    public JAXBElement<Amount> createSlot3(Amount value) {
        return new JAXBElement<Amount>(_Slot3_QNAME, Amount.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Amount }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "slot4")
    public JAXBElement<Amount> createSlot4(Amount value) {
        return new JAXBElement<Amount>(_Slot4_QNAME, Amount.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Amount }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "slot5")
    public JAXBElement<Amount> createSlot5(Amount value) {
        return new JAXBElement<Amount>(_Slot5_QNAME, Amount.class, null, value);
    }

}
