//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.10 at 10:15:41 PM EDT 
//


package net.edmacdonald.fantasyGrounds;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}id-00001" minOccurs="0"/>
 *         &lt;element ref="{}id-00002" minOccurs="0"/>
 *         &lt;element ref="{}id-00003" minOccurs="0"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element ref="{}id-00004"/>
 *           &lt;element ref="{}id-00005"/>
 *           &lt;element ref="{}id-00006"/>
 *           &lt;element ref="{}id-00007"/>
 *           &lt;element ref="{}id-00008"/>
 *         &lt;/sequence>
 *         &lt;sequence minOccurs="0">
 *           &lt;element ref="{}id-00009"/>
 *           &lt;element ref="{}id-00010"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id00001",
    "id00002",
    "id00003",
    "id00004",
    "id00005",
    "id00006",
    "id00007",
    "id00008",
    "id00009",
    "id00010"
})
@XmlRootElement(name = "power")
public class Power {

    @XmlElement(name = "id-00001")
    protected Id00001 id00001;
    @XmlElement(name = "id-00002")
    protected Id00002 id00002;
    @XmlElement(name = "id-00003")
    protected Id00003 id00003;
    @XmlElement(name = "id-00004")
    protected Id00004 id00004;
    @XmlElement(name = "id-00005")
    protected Id00005 id00005;
    @XmlElement(name = "id-00006")
    protected Id00006 id00006;
    @XmlElement(name = "id-00007")
    protected Id00007 id00007;
    @XmlElement(name = "id-00008")
    protected Id00008 id00008;
    @XmlElement(name = "id-00009")
    protected Id00009 id00009;
    @XmlElement(name = "id-00010")
    protected Id00010 id00010;

    /**
     * Gets the value of the id00001 property.
     * 
     * @return
     *     possible object is
     *     {@link Id00001 }
     *     
     */
    public Id00001 getId00001() {
        return id00001;
    }

    /**
     * Sets the value of the id00001 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Id00001 }
     *     
     */
    public void setId00001(Id00001 value) {
        this.id00001 = value;
    }

    /**
     * Gets the value of the id00002 property.
     * 
     * @return
     *     possible object is
     *     {@link Id00002 }
     *     
     */
    public Id00002 getId00002() {
        return id00002;
    }

    /**
     * Sets the value of the id00002 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Id00002 }
     *     
     */
    public void setId00002(Id00002 value) {
        this.id00002 = value;
    }

    /**
     * Gets the value of the id00003 property.
     * 
     * @return
     *     possible object is
     *     {@link Id00003 }
     *     
     */
    public Id00003 getId00003() {
        return id00003;
    }

    /**
     * Sets the value of the id00003 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Id00003 }
     *     
     */
    public void setId00003(Id00003 value) {
        this.id00003 = value;
    }

    /**
     * Gets the value of the id00004 property.
     * 
     * @return
     *     possible object is
     *     {@link Id00004 }
     *     
     */
    public Id00004 getId00004() {
        return id00004;
    }

    /**
     * Sets the value of the id00004 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Id00004 }
     *     
     */
    public void setId00004(Id00004 value) {
        this.id00004 = value;
    }

    /**
     * Gets the value of the id00005 property.
     * 
     * @return
     *     possible object is
     *     {@link Id00005 }
     *     
     */
    public Id00005 getId00005() {
        return id00005;
    }

    /**
     * Sets the value of the id00005 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Id00005 }
     *     
     */
    public void setId00005(Id00005 value) {
        this.id00005 = value;
    }

    /**
     * Gets the value of the id00006 property.
     * 
     * @return
     *     possible object is
     *     {@link Id00006 }
     *     
     */
    public Id00006 getId00006() {
        return id00006;
    }

    /**
     * Sets the value of the id00006 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Id00006 }
     *     
     */
    public void setId00006(Id00006 value) {
        this.id00006 = value;
    }

    /**
     * Gets the value of the id00007 property.
     * 
     * @return
     *     possible object is
     *     {@link Id00007 }
     *     
     */
    public Id00007 getId00007() {
        return id00007;
    }

    /**
     * Sets the value of the id00007 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Id00007 }
     *     
     */
    public void setId00007(Id00007 value) {
        this.id00007 = value;
    }

    /**
     * Gets the value of the id00008 property.
     * 
     * @return
     *     possible object is
     *     {@link Id00008 }
     *     
     */
    public Id00008 getId00008() {
        return id00008;
    }

    /**
     * Sets the value of the id00008 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Id00008 }
     *     
     */
    public void setId00008(Id00008 value) {
        this.id00008 = value;
    }

    /**
     * Gets the value of the id00009 property.
     * 
     * @return
     *     possible object is
     *     {@link Id00009 }
     *     
     */
    public Id00009 getId00009() {
        return id00009;
    }

    /**
     * Sets the value of the id00009 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Id00009 }
     *     
     */
    public void setId00009(Id00009 value) {
        this.id00009 = value;
    }

    /**
     * Gets the value of the id00010 property.
     * 
     * @return
     *     possible object is
     *     {@link Id00010 }
     *     
     */
    public Id00010 getId00010() {
        return id00010;
    }

    /**
     * Sets the value of the id00010 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Id00010 }
     *     
     */
    public void setId00010(Id00010 value) {
        this.id00010 = value;
    }

}
