//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.10 at 10:15:41 PM EDT 
//


package net.edmacdonald.fantasyGrounds;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}implement"/>
 *         &lt;element ref="{}weapon"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "implement",
    "weapon"
})
@XmlRootElement(name = "powerfocus")
public class Powerfocus {

    @XmlElement(required = true)
    protected Implement implement;
    @XmlElement(required = true)
    protected Weapon weapon;

    /**
     * Gets the value of the implement property.
     * 
     * @return
     *     possible object is
     *     {@link Implement }
     *     
     */
    public Implement getImplement() {
        return implement;
    }

    /**
     * Sets the value of the implement property.
     * 
     * @param value
     *     allowed object is
     *     {@link Implement }
     *     
     */
    public void setImplement(Implement value) {
        this.implement = value;
    }

    /**
     * Gets the value of the weapon property.
     * 
     * @return
     *     possible object is
     *     {@link Weapon }
     *     
     */
    public Weapon getWeapon() {
        return weapon;
    }

    /**
     * Sets the value of the weapon property.
     * 
     * @param value
     *     allowed object is
     *     {@link Weapon }
     *     
     */
    public void setWeapon(Weapon value) {
        this.weapon = value;
    }

}
