//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.10 at 10:15:41 PM EDT 
//


package net.edmacdonald.fantasyGrounds;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}atwillspecial"/>
 *         &lt;element ref="{}cantrip"/>
 *         &lt;element ref="{}channeldivinity"/>
 *         &lt;element ref="{}encounterspecial"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "atwillspecial",
    "cantrip",
    "channeldivinity",
    "encounterspecial"
})
@XmlRootElement(name = "powershow")
public class Powershow {

    @XmlElement(required = true)
    protected Atwillspecial atwillspecial;
    @XmlElement(required = true)
    protected Cantrip cantrip;
    @XmlElement(required = true)
    protected Channeldivinity channeldivinity;
    @XmlElement(required = true)
    protected Encounterspecial encounterspecial;

    /**
     * Gets the value of the atwillspecial property.
     * 
     * @return
     *     possible object is
     *     {@link Atwillspecial }
     *     
     */
    public Atwillspecial getAtwillspecial() {
        return atwillspecial;
    }

    /**
     * Sets the value of the atwillspecial property.
     * 
     * @param value
     *     allowed object is
     *     {@link Atwillspecial }
     *     
     */
    public void setAtwillspecial(Atwillspecial value) {
        this.atwillspecial = value;
    }

    /**
     * Gets the value of the cantrip property.
     * 
     * @return
     *     possible object is
     *     {@link Cantrip }
     *     
     */
    public Cantrip getCantrip() {
        return cantrip;
    }

    /**
     * Sets the value of the cantrip property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cantrip }
     *     
     */
    public void setCantrip(Cantrip value) {
        this.cantrip = value;
    }

    /**
     * Gets the value of the channeldivinity property.
     * 
     * @return
     *     possible object is
     *     {@link Channeldivinity }
     *     
     */
    public Channeldivinity getChanneldivinity() {
        return channeldivinity;
    }

    /**
     * Sets the value of the channeldivinity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Channeldivinity }
     *     
     */
    public void setChanneldivinity(Channeldivinity value) {
        this.channeldivinity = value;
    }

    /**
     * Gets the value of the encounterspecial property.
     * 
     * @return
     *     possible object is
     *     {@link Encounterspecial }
     *     
     */
    public Encounterspecial getEncounterspecial() {
        return encounterspecial;
    }

    /**
     * Sets the value of the encounterspecial property.
     * 
     * @param value
     *     allowed object is
     *     {@link Encounterspecial }
     *     
     */
    public void setEncounterspecial(Encounterspecial value) {
        this.encounterspecial = value;
    }

}
