//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.10 at 10:15:41 PM EDT 
//


package net.edmacdonald.fantasyGrounds;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}prop001"/>
 *         &lt;element ref="{}prop002" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "prop001",
    "prop002"
})
@XmlRootElement(name = "props")
public class Props {

    @XmlElement(required = true)
    protected Prop001 prop001;
    protected Prop002 prop002;

    /**
     * Gets the value of the prop001 property.
     * 
     * @return
     *     possible object is
     *     {@link Prop001 }
     *     
     */
    public Prop001 getProp001() {
        return prop001;
    }

    /**
     * Sets the value of the prop001 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Prop001 }
     *     
     */
    public void setProp001(Prop001 value) {
        this.prop001 = value;
    }

    /**
     * Gets the value of the prop002 property.
     * 
     * @return
     *     possible object is
     *     {@link Prop002 }
     *     
     */
    public Prop002 getProp002() {
        return prop002;
    }

    /**
     * Sets the value of the prop002 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Prop002 }
     *     
     */
    public void setProp002(Prop002 value) {
        this.prop002 = value;
    }

}
